### ISSUE TITLE
0.2.28 run hello example fail

### ISSUE THREAD

**Issue by itmuse** [alephjs/aleph.js#115]
aleph dev
Download https://esm.x-static.io/v15/terser@5.3.2/esnext/terser.js
Download https://esm.x-static.io/v15/terser@5.3.2/tools/terser.d.ts
Download https://esm.x-static.io/v15/postcss@8.1.4/esnext/postcss.js
Download https://esm.x-static.io/v15/postcss@8.1.4/lib/postcss.d.ts
Download https://esm.x-static.io/v15/marked@1.2.0/esnext/marked.js
Download https://esm.x-static.io/v15/@types/marked@1.2.1/index.d.ts
Download https://esm.x-static.io/v15/clean-css@4.2.3/esnext/clean-css.js?no-check
Download https://esm.x-static.io/v15/yaml-front-matter@4.1.0/esnext/yaml-front-matter.js
Download https://esm.x-static.io/v15/@types/yaml-front-matter@4.1.0/index.d.ts
Download https://esm.x-static.io/v15/react@17.0.1/esnext/react.js
Download https://esm.x-static.io/v15/@types/react@17.0.0/index.d.ts
Download https://esm.x-static.io/v15/react-refresh-typescript@1.1.0/external=typescript@4.1.2/esnext/react-refresh-typescript.js
Download https://esm.x-static.io/v15/react-refresh-typescript@1.1.0/dist-types/index.d.ts
Download https://esm.x-static.io/v15/typescript@4.1.2/esnext/typescript.js
Download https://esm.x-static.io/v15/typescript@4.1.2/lib/typescript.d.ts
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) TypeError: Error: Unable to resolve media type for specifier: "https://esm.x-static.io/v15/@types/react@17.0.0/index.d.ts"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:235:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:318:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105298:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105536:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:105650:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:107137:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:106909:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:106771:26)
    at deno:cli/tsc/00_typescript.js:106728:85

**Comment by ije** [comment]
@itmuse  which Deno version you are using?

**Comment by ije** [comment]
i am going to close this since 0.2.28 is outdated.
