### ISSUE TITLE
Can't get Aleph.js working

### ISSUE THREAD

**Issue by lcswillems** [alephjs/aleph.js#180]
I am on Kubuntu 20.04. 

I executed these commands:

```sh
# Install Deno
curl -fsSL https://deno.land/x/install/install.sh | sh
# Install Aleph
deno install -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
# Create Aleph app
aleph init hello
# Move inside the app
cd hello
```

Then when I execute `aleph dev`. I get this error:

```
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) TypeError: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:96:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:111:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:135:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:160:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:183:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.89.0/fs/copy.ts:214:10

TS2339 [ERROR]: Property 'systemMemoryInfo' does not exist on type 'typeof Deno'. 'Deno.systemMemoryInfo' is an unstable API. Did you forget to run with the '--unstable' flag?
  return Deno.systemMemoryInfo().free;
              ~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.89.0/node/os.ts:128:15

TS2339 [ERROR]: Property 'loadavg' does not exist on type 'typeof Deno'. 'Deno.loadavg' is an unstable API. Did you forget to run with the '--unstable' flag?
  return Deno.loadavg();
              ~~~~~~~
    at https://deno.land/std@0.89.0/node/os.ts:152:15

TS2339 [ERROR]: Property 'osRelease' does not exist on type 'typeof Deno'. 'Deno.osRelease' is an unstable API. Did you forget to run with the '--unstable' flag?
  return Deno.osRelease();
              ~~~~~~~~~
    at https://deno.land/std@0.89.0/node/os.ts:166:15

TS2339 [ERROR]: Property 'systemMemoryInfo' does not exist on type 'typeof Deno'. 'Deno.systemMemoryInfo' is an unstable API. Did you forget to run with the '--unstable' flag?
  return Deno.systemMemoryInfo().total;
              ~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.89.0/node/os.ts:190:15

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
  signals: Deno.Signal,
                ~~~~~~
    at https://deno.land/std@0.89.0/node/os.ts:228:17

Found 11 errors.
    const { default: cmd } = await import(`./cli/${command}.ts`)
                             ^
    at async main (https://deno.land/x/aleph@v0.2.28/cli.ts:163:30)
```

**Comment by FallingSnow** [comment]
Use the `--unstable` flag when installing.

```
deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
```
