### ISSUE TITLE
aleph 0.2.28 issue with last version of esm.sh

### ISSUE THREAD

**Issue by RoXuS** [alephjs/aleph.js#182]
Hi team,

We have an issue with last version of esm.sh (v16). When we start aleph dev we have the following error:
![image](https://user-images.githubusercontent.com/3296671/110377985-55809e00-8055-11eb-868e-457bcc780d0b.png)

Seems to be linked to https://github.com/postui/esm.sh/issues/27.

**Comment by vincent-olivert-riera** [comment]
For me, it fails even with esm v21. This looks like an important bug since it's breaking the most basic thing. Look:

```
$ deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
$ aleph init hello
$ cd hello
$ aleph dev
[snip]
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
Download https://esm.sh/autoprefixer?external=postcss@8.1.4&no-check
Download https://cdn.esm.sh/v21/autoprefixer@10.2.5/external=postcss@8.1.4/deno/autoprefixer.js?no-check
error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
        Object.assign(globalThis, {
               ^
    at Function.assign (<anonymous>)
    at Project._init (https://deno.land/x/aleph@v0.2.28/project.ts:600:16)
    at async https://deno.land/x/aleph@v0.2.28/project.ts:106:13
    at async start (https://deno.land/x/aleph@v0.2.28/server.ts:12:5)
```

**Comment by ije** [comment]
fixed
