### ISSUE TITLE
"Get Started" instructions are broken

### ISSUE THREAD

**Issue by vincent-olivert-riera** [alephjs/aleph.js#190]
I just tried to do exactly what the instructions from https://alephjs.org/docs/get-started say:

```
deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
aleph init hello
cd hello
aleph dev
```

But that resulted on this error:

```
error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
        Object.assign(globalThis, {
               ^
    at Function.assign (<anonymous>)
    at Project._init (https://deno.land/x/aleph@v0.2.28/project.ts:600:16)
    at async https://deno.land/x/aleph@v0.2.28/project.ts:106:13
    at async start (https://deno.land/x/aleph@v0.2.28/server.ts:12:5)
```

**Comment by RazerMoon** [comment]
I also got the same error

**Comment by borsemayur2** [comment]
This is related to Deno 1.8.0. Downgrade Deno to 1.7.5 to run the app

**Comment by borsemayur2** [comment]
> 
> 
> I just tried to do exactly what the instructions from https://alephjs.org/docs/get-started say:
> 
> ```
> deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
> aleph init hello
> cd hello
> aleph dev
> ```
> 
> But that resulted on this error:
> 
> ```
> error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
>         Object.assign(globalThis, {
>                ^
>     at Function.assign (<anonymous>)
>     at Project._init (https://deno.land/x/aleph@v0.2.28/project.ts:600:16)
>     at async https://deno.land/x/aleph@v0.2.28/project.ts:106:13
>     at async start (https://deno.land/x/aleph@v0.2.28/server.ts:12:5)
> ```

Use aleph version  v0.3.0-alpha.0 instead of v0.2.28 like:
`deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts`

**Comment by ije** [comment]
@vincent-olivert-riera @RazerMoon @borsemayur2  i'm so sorry, currently you should use v0.2.28 + deno **1.6.3**, the alpha versions is super unstable...the next patch (beta.1) i'm working on it should be more stable!
PR: https://github.com/alephjs/aleph.js/pull/176

**Comment by mellisdesigns** [comment]
I have just recently run into an issue running Aleph JS using the cli for an existing project (and a newly created project to sanity check) on OSX, 11.2.1 (Big Sur)

`aleph --version`
![image](https://user-images.githubusercontent.com/629570/111050841-1b732a00-84a3-11eb-95b0-7381fb780a79.png)

`deno --version`
![image](https://user-images.githubusercontent.com/629570/111050849-26c65580-84a3-11eb-9c55-43837f155afc.png)

When I run `aleph dev` in a brand new project I get
![image](https://user-images.githubusercontent.com/629570/111050864-3cd41600-84a3-11eb-8bad-c624bdf47001.png)

**Comment by konsumer** [comment]
I am trying to get started with aleph, and follow the advice here. My goal is to put all the version-lockin stuff in a Makefile, so we have a known-working combo of versions of things, that is reproducible on every machine. 

I use docker to lock-in versions:

```
docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.6.3 deno run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts --version

aleph.js 0.2.28
deno 1.6.3
v8 8.8.294
typescript 4.1.3

docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.6.3 deno run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts init testapp

INFO Aleph.js is ready to Go.
INFO $ cd testapp
INFO $ aleph dev    # start the app in `development` mode
INFO $ aleph start  # start the app in `production` mode
INFO $ aleph build  # build the app to a static site (SSG)

docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.6.3 deno run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts dev /app/testapp

error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async open (deno:runtime/js/30_files.js:44:17)
    at async Object.readFile (deno:runtime/js/40_read_file.js:15:18)
    at async Project._compile (project.ts:1022:29)
    at async Project._compile (project.ts:1172:28)
    at async Project._init (project.ts:658:21)
    at async project.ts:106:13
    at async start (server.ts:12:5)
```

Same with `dev testapp`.

I also tried this, inside the dir it initted before:
```
docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.6.3 sh
deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
/usr/local/bin/aleph --version

aleph.js 0.2.28
deno 1.6.3
v8 8.8.294
typescript 4.1.3

/usr/local/bin/aleph start
```

And I get same error. Am I missing some other part?

**Comment by shadowtime2000** [comment]
@mellisdesigns Your error is due to problems in esm.sh, please try again and if it doesn't work open an issue in the esm.sh repo

**Comment by konsumer** [comment]
My issue seems like #195 so maybe that is a better place to track it.

**Comment by macorifice** [comment]
I have the same issue
```shell
aleph.js 0.2.28
deno 1.8.1
v8 9.0.257.3
typescript 4.2.2
```

With this error
```shell
error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
        Object.assign(globalThis, {
               ^
    at Function.assign (<anonymous>)
    at Project._init (https://deno.land/x/aleph@v0.2.28/project.ts:600:16)
    at async https://deno.land/x/aleph@v0.2.28/project.ts:106:13
    at async start (https://deno.land/x/aleph@v0.2.28/server.ts:12:5)
```

**Comment by shadowtime2000** [comment]
@macorifice Try downgrading to Deno 1.6.3 for that.

**Comment by macorifice** [comment]
```shell
➜ aleph --version
aleph.js 0.2.28
deno 1.6.3
v8 8.8.294
typescript 4.1.3
```

![image](https://user-images.githubusercontent.com/2563910/111599155-45448d80-87d0-11eb-9004-7fdc8353e764.png)

**Comment by konsumer** [comment]
@macorifice same as me. I think it's tracked in #195

**Comment by macorifice** [comment]
> #195

I think it's a little bit different cuz in your case the server started, in my case, it didn't found any files or directories

**Comment by konsumer** [comment]
@macorifice  Not sure what you mean. I got same error, and it also didn't start. I just gave detailed instructions to test with docker with the suggested versions.

**Comment by macorifice** [comment]
@konsumer you're right! I only saw the first part of 195 and saw the server started, then I realized that you are referring to the continuation

**Comment by arctix-tk** [comment]
hey guys,
I'm getting following error using aleph.js 0.3.0-alpha.22:  os error 123 "The filename, directory name, or volume label syntax is incorrect", also tried using deno: 1.8.2 -> same error, OS= Win10, I also followed the docs, (deno:1.6.3 and alpeh v0.2.28) didn't seem to work either -> same error as described in the first comment. Any help would be greatly appreciated.
![image](https://user-images.githubusercontent.com/53367965/113458845-fb84b580-9413-11eb-94e4-8c2f1346a87d.png)

**Comment by borsemayur2** [comment]
> 
> 
> hey guys,
> I'm getting following error using aleph.js 0.3.0-alpha.22: os error 123 "The filename, directory name, or volume label syntax is incorrect", also tried using deno: 1.8.2 -> same error, OS= Win10, I also followed the docs, (deno:1.6.3 and alpeh v0.2.28) didn't seem to work either -> same error as described in the first comment. Any help would be greatly appreciated.
> ![image](https://user-images.githubusercontent.com/53367965/113458845-fb84b580-9413-11eb-94e4-8c2f1346a87d.png)

I'm getting the same error with both (alpha.22 and alpha.24) on Win10. But Able to run the app in WSL2. The Error seems to be related with Deno runtime API.

**Comment by shadowtime2000** [comment]
@borsemayur2 @arctix-tk The error you are experiencing is #201.

**Comment by gauravnumber** [comment]
You all guys don't you need downgrade Deno. Just upgrade Deno v1.9.2 it worked.
Previously I using Deno v1.6.3 and I got the same error since upgrading deno it work well now.

**Comment by konsumer** [comment]
@gauravnumber I got it to run `init`, but it failed to run dev. What versions of things are you using?

Here is my test procedure:

```
docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.9.2 deno run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts --version

aleph.js 0.2.28
deno 1.9.2
v8 9.1.269.5
typescript 4.2.2

# works ok now:
docker run -v ${PWD}:/app --workdir=/app -it --init hayd/alpine-deno:1.9.2 deno run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts init testapp

docker run -v ${PWD}:/app --workdir=/app/testrun -it --init hayd/alpine-deno:1.9.2 run --unstable -A https://deno.land/x/aleph@v0.2.28/cli.ts dev
```

I get this error:

```
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type 'TransformerFactory<SourceFile>' is not assignable to parameter of type 'TransformerFactory<SourceFile> | CustomTransformerFactory'.
  Type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").SourceFile>' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").SourceFile>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").TransformationContext' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").TransformationContext'.
        The types of 'factory.createTypeParameterDeclaration(...).parent' are incompatible between these types.
          Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").InferTypeNode' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").InferTypeNode'.
            Type 'JSDocTemplateTag' is not assignable to type 'DeclarationWithTypeParameterChildren | InferTypeNode'.
              Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").JSDocTemplateTag' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").JSDocTemplateTag'.
                Types of property 'parent' are incompatible.
                  Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").JSDocTypeLiteral' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").JSDocTypeLiteral'.
                    Type 'JSDoc' is not assignable to type 'JSDoc | JSDocTypeLiteral'.
                      Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").JSDoc' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").JSDoc'.
                        Types of property 'parent' are incompatible.
                          Type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").HasJSDoc' is not assignable to type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").HasJSDoc'.
                            Type 'ImportEqualsDeclaration' is not assignable to type 'HasJSDoc'.
                              Property 'isTypeOnly' is missing in type 'import("https://cdn.esm.sh/v41/typescript@4.1.2/lib/typescript.d.ts").ImportEqualsDeclaration' but required in type 'import("https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts").ImportEqualsDeclaration'.
    if (reactRefresh) transformers.before!.push(reactRefreshTS())
                                                ~~~~~~~~~~~~~~~~
    at https://deno.land/x/aleph@v0.2.28/tsc/compile.ts:28:49

    'isTypeOnly' is declared here.
            readonly isTypeOnly: boolean;
                     ~~~~~~~~~~
        at https://cdn.esm.sh/v41/typescript@4.2.4/lib/typescript.d.ts:1601:18
    const { default: cmd } = await import(`./cli/${command}.ts`)
                             ^
    at async main (https://deno.land/x/aleph@v0.2.28/cli.ts:163:30)
```

**Comment by gauravnumber** [comment]
You may need upgrade Aleph.js.
Try this 
```
docker run -v ${PWD}:/app --workdir=/app/testrun -it --init hayd/alpine-deno:1.9.2 run --unstable -A https://deno.land/x/aleph@v0.3.0-alpha.32/cli.ts dev
```

**Comment by konsumer** [comment]
@gauravnumber That is using latest stable, but I'm fine with alpha, too, though. This does seem to start:
```
docker run -p 8080:8080 -v ${PWD}:/app --workdir=/app/testrun -it --init hayd/alpine-deno:1.9.2 run --unstable -A https://deno.land/x/aleph@v0.3.0-alpha.32/cli.ts dev

... download stuff...

INFO Compiling...
INFO Start watching code changes...
INFO Server ready on http://localhost:8080/
```
also leaving out `--init`, neither serves anything on port 8080, though. Am I missing something else? Did you test this?

**Comment by konsumer** [comment]
Huh, nevermind, maybe it is working. the `--init` thing seemed lock up my terminal on mac, so I killed the docker daemon, and restarted, and ran the same command again. It did seem to get further. I get "Page Not Found", but maybe that is expected? It appears to at least be servicing the error.

**Comment by slashwhatever** [comment]
Still broken for me

```
aleph.js 0.3.0-alpha.8
deno 1.22.0
v8 10.0.139.17
typescript 4.6.2
```
