### ISSUE TITLE
AssertionError: "data" is unexpectedly null for "/v23/_node.ns.d.ts". when running `pnpm dev`

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/aleph.js#196]
## Error stacktrace

```
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) TypeError: AssertionError: "data" is unexpectedly null for "/v23/_node.ns.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:67:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:279:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:108104:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:108014:26)
    at deno:cli/tsc/00_typescript.js:107966:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:107933:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:107966:13)
    at deno:cli/tsc/00_typescript.js:108252:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:384:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:108251:16)
    const { default: cmd } = await import(`./cli/${command}.ts`)
                             ^
    at async main (https://deno.land/x/aleph@v0.2.28/cli.ts:163:30)
```

## Reproduction

- `aleph init hello`
- `cd hello`
- `aleph dev`

## Useful info
- Deno version: 1.8.0
- Aleph version: 0.2.28

**Comment by shadowtime2000** [comment]
Seems to be a bug with ESM

cc @ije

**Comment by ije** [comment]
fixed in **v24**

**Comment by talentlessguy** [comment]
@ije now it throws this:

```
error: Uncaught (in promise) TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'
    Object.assign(globalThis, {
           ^
    at Function.assign (<anonymous>)
    at Application.init (https://deno.land/x/aleph@v0.3.0-alpha.8/server/app.ts:410:12)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.8/server/server.ts:177:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts:21:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts:147:7)
```

**Comment by shadowtime2000** [comment]
@talentlessguy That error occurs because Deno 1.8.0 started adding web APIs to navigator forcing us to change how we modified it, try using Deno.1.7.x

**Comment by talentlessguy** [comment]
@ije will it support Deno 1.8 in the future? I don't want to stick 1.7 forever :(

**Comment by shadowtime2000** [comment]
@talentlessguy It's Deno 1.8.0 compatable on `master`, so next release will work with 1.8
