### ISSUE TITLE
Sass error (cannot read property 'indexOf' of undefined)

### ISSUE THREAD

**Issue by creepinson** [alephjs/aleph.js#200]
It seems to error when I try to use the sass plugin. 

Error:

```
❯ aleph dev
error: Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:193:34913
    at Object.applyHooksTransformer (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:65767)
    at Object.initHooks (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:65256)
    at Object.initNativeDispatchContinue (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:64495)
    at Object.initNativeDispatch (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:64295)
    at Object.getNativeInterceptor (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:96024)
    at Object.getInterceptor$x (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:100327)
    at Object.set$render$x (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:3:101171)
    at Object.main0 (https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:67:40750)
    at https://cdn.esm.sh/v26/sass@1.32.5/deno/sass.js:196:83657
```

**aleph.config.js:**

```typescript**
import sass from "https://deno.land/x/aleph/plugins/sass.ts";

export default {
    plugins: [sass],
};
```

**Comment by creepinson** [comment]
This actually might have to do with the Deno or Aleph version, as I can see from other issues. I got another error after removing the sass plugin that is mentioned  in another issue.

**Comment by shadowtime2000** [comment]
@creepinson Can you share your Deno and Aleph version? Seems to just be a problem with the conversion from esm.sh

**Comment by creepinson** [comment]
> @creepinson Can you share your Deno and Aleph version? Seems to just be a problem with the conversion from esm.sh

Pretty sure I used the latest version from the docs or something. I kept having multiple issues with Aleph so I tried to reinsatll it just now with **both** the  v3 alpha.8 and the v0.2.28 and both of them give this error that was mentioned in other issues.

```
error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
    Object.assign(globalThis, {
           ^
    at Function.assign (<anonymous>)
    at Application.init (https://deno.land/x/aleph@v0.3.0-alpha.8/server/app.ts:410:12)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.8/server/server.ts:177:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts:21:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts:147:7)

```

**Comment by creepinson** [comment]
I tried before with deno 1.6.3 but still had similar errors like these that I can't reproduce right now.

**Comment by ije** [comment]
i already removed the sass plugin since it can't work in deno fine. will re-add it in the future when it suppports deno.
