### ISSUE TITLE
Windows: os error 123

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#201]
Works fine under wsl, but with windows + powershell I get this kind of error.
```
❯ aleph --version
aleph.js 0.3.0-alpha.12
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2

❯ aleph dev
INFO Config loaded from aleph.config.ts
INFO Compiling...
error: Uncaught (in promise) Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at asyncHandle (deno:core/core.js:223:40)
    at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
    at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

**Comment by ije** [comment]
did't test on windows yet, will test it later thanks @KotlinIsland

**Comment by Hunam6** [comment]
I'm on Windows too and I have the exact same issue.

**Comment by ije** [comment]
fixed in **alpha.25**, pls upgrade the alephjs: `aleph upgrade`
