### ISSUE TITLE
Adding a 'src' folder to the project causes 'No such file or directory (os error 2)'

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#207]
```ts
> aleph dev
INFO Config loaded from aleph.config.ts
INFO Compiling...
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at asyncHandle (deno:core/core.js:223:40)
    at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
    at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

**Comment by ije** [comment]
fixed, pls upgrade to alpha.15, thanks 🙏
