### ISSUE TITLE
Wrong build operation

### ISSUE THREAD

**Issue by vincenzopalazzo** [alephjs/aleph.js#211]
I run the build operation and I receive the following error when I tried to build run this on my evn.

![Selection_076](https://user-images.githubusercontent.com/17150045/112558941-2e092f80-8dd0-11eb-93f5-00ecb9d7561e.png)

Deno version: 
deno 1.8.2 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2

Aleph version
Aleph 3.14159265-1.15-2.1-0.1 (TeX Live 2019/Debian)

If I can help, please point me and I'm open to support this project with my work

## Update

This problem is the same with the `start` command, but I can work with `dev`, my app is available [here](https://github.com/clightning4j/ln-sanitycheck) if you want to make some tests

in dev mode, I receive the following error that is thrown from the library MaterialUI during the translating function

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at ButtonBase2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:8612:24)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at IconButton2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:8938:29)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at div
    at Toolbar2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:24968:25)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at header
    at Paper2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:8001:25)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at AppBar2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:9187:25)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at div
    at Container2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:12068:25)
    at WithStyles2 (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6542:37)
    at Home (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/pages/index.js#161a8a:11:73)
    at ThemeProvider (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/-/cdn.esm.sh/v28/@material-ui/core@4.11.3/deno/core.development.js:6467:26)
    at main
    at App (file:///home/vincent/Github/clightning4j/ln-sanitycheck/.aleph/development/app.js#d33614:23:31)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```

**Comment by ije** [comment]
try `npx serve`after build since we use absolute path to import script in the built html. thanks @vincenzopalazzo  i will try your example

**Comment by vincenzopalazzo** [comment]
@ije I ran your command in the root directory and I receive the same error, and after I moved in the dist directory and I run the command again.

I receive the following error

![Selection_077](https://user-images.githubusercontent.com/17150045/112619536-be269380-8e27-11eb-8da5-d47b242dc5b4.png)

**Comment by ije** [comment]
this is the react-dom and react url did not match by esm.sh update, in latest updates, alephjs will check the dismatch url and fix it automatically.

**Comment by vincenzopalazzo** [comment]
Thanks, @ije I will punt in my queue task to test the last version of this framework.

**Comment by vincenzopalazzo** [comment]
ack @ije
