### ISSUE TITLE
Warning on using Zustand

### ISSUE THREAD

**Issue by aadamsx** [alephjs/aleph.js#221]
I'm trying out Zustand with Aleph and get this warning on render:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at People (file:///Users/aadams/Projects/ms-email/.aleph/development/components/People.js#/components/People.tsx@1818f4:7:20)
    at main
    at App (file:///Users/aadams/Projects/ms-email/.aleph/development/app.js#543810:5:31)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at People (file:///Users/aadams/Projects/ms-email/.aleph/development/components/People.js#/components/People.tsx@1818f4:7:20)
    at main
    at App (file:///Users/aadams/Projects/ms-email/.aleph/development/app.js#543810:5:31)
```

```
$ aleph --version
aleph.js 0.3.0-alpha.22
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
```

My code: https://github.com/aadamsx/aleph-error3

**Comment by aadamsx** [comment]
Note: Strange to me that I did an ```aleph upgrade``` and an ```aleph dev --reload``` and my in my ```import_map.json``` still shows ```alpha 12``` and ```react 17.0.1```.

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.12/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.12/",
        "react": "https://esm.sh/react@17.0.1",
        "react-dom": "https://esm.sh/react-dom@17.0.1"
    },
    "scopes": {}
}
```

I how does Aleph resolve the issue where Zustand is using React 17.0.2 and Aleph is using React 17.0.1?

**Comment by shadowtime2000** [comment]
@aadamsx afaik Aleph isn't going to automatically change the import map, your going to have to do that yourself.

**Comment by aadamsx** [comment]
> @aadamsx afaik Aleph isn't going to automatically change the import map, your going to have to do that yourself.

Then what did aleph dev -reload do for me to get the inconsistencies between libs straight?

**Comment by aadamsx** [comment]
Also, I changed the import map to this:

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.22/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.22/",
        "react": "https://esm.sh/react@17.0.2",
        "react-dom": "https://esm.sh/react-dom@17.0.2"
    },
    "scopes": {}
}
```

and afterwards did an ```aleph dev -reload``` and get an error on that command: ```ERROR Fetch module 'https://deno.land/x/aleph@v0.3.0-alpha.22/react.ts': Not Found```

**Comment by ije** [comment]
you shouldn't use `useLayoutEffect` in SSR mode
fyi https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85

**Comment by aadamsx** [comment]
@ije so what does SSR mode actually mean in the Aleph context?  

The library that's causing the ```useLayoutEffect``` error is actually the redux-like state management library [Zustand](https://github.com/pmndrs/zustand) library I'm importing.  I've imported this into the ```/lib``` directory as you can see here: https://github.com/aadamsx/aleph-error3/blob/master/lib/useStore.ts

How do you handle this situation?  I need the client-side state-management library in this component: https://github.com/aadamsx/aleph-error3/blob/master/components/People.tsx, but of course it loads server side due to the way Aleph renders.

**Comment by shadowtime2000** [comment]
@aadamsx 

> but of course it loads server side due to the way Aleph renders.

This is the way most frameworks like Next and Gatsby do to. It isn't something that we can change - your just going to have to look on how you change the loading of the state management library.

**Comment by aadamsx** [comment]
@ije @shadowtime2000 It's Zustand that's using ```useLayoutEffect``` but they said they're looking for the window object before decding which hook to use: https://github.com/pmndrs/zustand/issues/347#issuecomment-810654489 (useEffect or useLayoutEffect)

What do you make of this?

**Comment by ije** [comment]
let make PR to zustand to support deno

**Comment by ije** [comment]
https://github.com/pmndrs/zustand/pull/348

**Comment by aadamsx** [comment]
@ije looks like that [PR](pmndrs/zustand#348) might not have worked (I tested it).  What to do in this case since Deno has ```window``` defined?  I guess the question is, distinguish if you're on the server or client when Deno as the server?

**Comment by aadamsx** [comment]
@ije how are you debugging Aleph inside Visual Studio code?  I don't have the settings set up for it.  When I try Deno: Run I get:

```
Note: Using the "preview" debug extension
/usr/local/bin/deno run --unstable --inspect --allow-all main.ts
Debugger listening on ws://127.0.0.1:9229/ws/374009d0-83a0-43ef-ac8b-6b036bb2dc0a
error: Cannot resolve module "file:///Users/aadams/Projects/mserv-mail/main.ts".
Process exited with code 1
```

**Comment by aadamsx** [comment]
If I change the launch.json to make the program entry point app.tsx like so:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Deno: Run",
      "request": "launch",
      "type": "pwa-node",
      "program": "app.tsx",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "run",
        "--unstable",
        "--inspect",
        "--allow-all"
      ],
      "attachSimplePort": 9229
    }
  ]
}
```

I get the following error message:

```
Debugger listening on ws://127.0.0.1:9229/ws/ee7c5721-4a69-4ea8-89c5-09fc8a0c3393
Check file:///Users/aadams/Projects/mserv-mail/app.tsx
error: TS2339 [ERROR]: Property 'document' does not exist on type 'Window & typeof globalThis'.
  console.log(window.document);
                     ~~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:5:22

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
    <div>
    ~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:8:5

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <p>Test</p>
      ~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:9:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <p>Test</p>
             ~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:9:14

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <p>We have { people.length } people in our DB </p>
      ~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:10:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <p>We have { people.length } people in our DB </p>
                                                    ~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:10:53

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <ul>
      ~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:11:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
        {people.map((p: any) => <li key='{p}'>{p}</li>)}
                                ~~~~~~~~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:12:33

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
        {people.map((p: any) => <li key='{p}'>{p}</li>)}
                                                 ~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:12:50

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      </ul>
      ~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:13:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
    </div>
    ~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/components/People.tsx:14:5

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'ComponentType'.
import React, { ComponentType } from 'react'
                ~~~~~~~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:1:17

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
    <main>
    ~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:6:5

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <head>
      ~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:7:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
        <meta name="viewport" content="width=device-width" />
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:8:9

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      </head>
      ~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:9:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
    </main>
    ~~~~~~~
    at file:///Users/aadams/Projects/mserv-mail/app.tsx:12:5

Found 17 errors.
Process exited with code 1
```

This error tells me Deno doesn't understand the entry point: ```error: TS2339 [ERROR]: Property 'document' does not exist on type 'Window & typeof globalThis'.```
