### ISSUE TITLE
[bug] Can't compile the template project

### ISSUE THREAD

**Issue by satanya-zero** [alephjs/aleph.js#224]
```
error: Uncaught Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at asyncHandle (deno:core/core.js:223:40)
    at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
    at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

OS: Windows 10

**Comment by shadowtime2000** [comment]
@satanya-zero Can you share what commands you ran to get that error and what version of Deno and Aleph you are using, and basically reproduction steps?

**Comment by ije** [comment]
@satanya-zero sorry, i never tested on windows port, but will do it ASAP, thanks. currently the unit testing was passed on ci/windows but it is weak can not check everything, i will add more tests in the future

**Comment by satanya-zero** [comment]
> @satanya-zero Can you share what commands you ran to get that error and what version of Deno and Aleph you are using, and basically reproduction steps?

deno 1.8.2 (release, x86_64-pc-windows-msvc)
aleph.js v0.3.0-alpha.22

```
PS > aleph init template
Add recommended workspace settings of VS Code? [y/n] y
Downloading template...
Saving template...
Done
---
Aleph.js is ready to go!
$ cd template
$ aleph dev     # start the app in `development` mode
$ aleph start   # start the app in `production` mode
$ aleph build   # build the app to a static site (SSG)
---
PS > cd .\template\
PS > aleph dev
error: Uncaught Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at asyncHandle (deno:core/core.js:223:40)
    at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
    at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

**Comment by Hunam6** [comment]
Duplicate as #201
