### ISSUE TITLE
500 - Cannot read property 'toString' of undefined with <a> tag

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#227]
```ts
import React from 'react'

export default function Home() {

  return (
    <a>asdf</a>
  )
}
```

**Comment by shadowtime2000** [comment]
@KotlinIsland Can you provide more details like what a command you ran, what your import map looks like, what you did before that, operating system, aleph version, deno version, and just reproduction steps?

**Comment by KotlinIsland** [comment]
```
> aleph --version
aleph.js 0.3.0-alpha.22
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
```
WSL Ubuntu-20.04
this is just `aleph init` and  `aleph dev`

**Comment by KotlinIsland** [comment]
```
TypeError: Cannot read property 'toString' of undefined
    at http://localhost:8080/_aleph/-/deno.land/x/aleph@v0.3.0-alpha.22/framework/react/anchor.js:29:26
    at mountMemo (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:12625:33)
    at Object.useMemo (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:12932:36)
    at useMemo2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react@17.0.1/deno/react.development.js:1106:35)
    at Anchor (http://localhost:8080/_aleph/-/deno.land/x/aleph@v0.3.0-alpha.22/framework/react/anchor.js:26:25)
    at renderWithHooks (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:12009:32)
    at mountIndeterminateComponent (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:14190:29)
    at beginWork (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:14989:36)
    at HTMLUnknownElement.callCallback2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:4267:34)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/_aleph/-/cdn.esm.sh/v28/react-dom@17.0.1/deno/react-dom.development.js:4292:34)
```

**Comment by ije** [comment]
sorry, i did some breaking changes in latest updates of esm.sh, i believe the v33 should work

**Comment by ije** [comment]
https://github.com/postui/esm.sh/issues/41

**Comment by KotlinIsland** [comment]
@ije nope, still same thing.

**Comment by ije** [comment]
please clean deno cache, or `aleph dev --reload`

**Comment by KotlinIsland** [comment]
Same thing.

**Comment by KotlinIsland** [comment]
Can you try reproduce?

**Comment by ije** [comment]
<img width="994" alt="Screen Shot 2021-03-30 at 12 53 34 PM" src="https://user-images.githubusercontent.com/2883484/112935747-fa733000-9156-11eb-9f30-e589461cf72f.png">
is it v33?

**Comment by KotlinIsland** [comment]
yes
![Uploading image.png…]()

**Comment by KotlinIsland** [comment]
![image](https://user-images.githubusercontent.com/65446343/112935869-fb608d80-9167-11eb-9844-f7e3f7bf3e20.png)

**Comment by KotlinIsland** [comment]
It's this line:
```ts
const currentHref = useMemo(() => {
    return [currentPathname, currentQuery.toString()].filter(Boolean).join('?')
  }, [currentPathname, currentQuery])
```

**Comment by ije** [comment]
seems the `currentQuery` is undefined, what is it for?

**Comment by KotlinIsland** [comment]
I have no idea :)

**Comment by KotlinIsland** [comment]
That's from aleph/framework/react/anchor.ts

**Comment by ije** [comment]
oh, my mistake, will fix it!

**Comment by stereosteve** [comment]
FYI using `v0.3.0-alpha.23` ... clicking on a `<a href="/about">about</a>` does nothing.  Suspect it's related!

**Comment by ije** [comment]
@stereosteve thanks, I will fix it as soon asap!

**Comment by ije** [comment]
up to **alpha.24** to fix this! thanks all
