### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot resolve module with `aleph start`

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#228]
```
> aleph --version
aleph.js 0.3.0-alpha.22
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2

> aleph start
Download https://esm.sh/terser@5.6.1?no-check
INFO Download https://cdn.esm.sh/v32/react@17.0.1/deno/react.js
ERROR Fetch module 'https://cdn.esm.sh/v32/react@17.0.1/deno/react.js': Internal Server Error
error: Uncaught (in promise) TypeError: Cannot resolve module "file:///home/user/projects/test/.aleph/production/-/cdn.esm.sh/v32/react@17.0.1/deno/react.js" from "file:///home/user/projects/test/.aleph/production/-/cdn.esm.sh/v32/react-dom@17.0.1/deno/server.js".
    at file:///home/user/projects/test/.aleph/production/-/cdn.esm.sh/v32/react-dom@17.0.1/deno/server.js:1:0
      const { render } = await import(`file://${jsFile}`)
                         ^
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.22/server/app.ts:195:26)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.22/server/server.ts:208:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.22/cli/start.ts:33:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.22/cli.ts:122:3)
```

**Comment by TranquilMarmot** [comment]
Similar issue here...

```
> aleph --version
aleph.js 0.3.0-alpha.20
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
> aleph dev
Download https://esm.sh/terser@5.6.1?no-check
INFO Download https://esm.sh/react@17.0.1
ERROR Fetch module 'https://esm.sh/react@17.0.1': Internal Server Error
INFO Download https://cdn.esm.sh/v32/react@17.0.1/deno/react.development.js
ERROR Fetch module 'https://cdn.esm.sh/v32/react@17.0.1/deno/react.development.js': Internal Server Error
INFO Download https://esm.sh/react@17.0.1
ERROR Fetch module 'https://esm.sh/react@17.0.1': Internal Server Error
INFO Download https://esm.sh/react@17.0.1
ERROR Fetch module 'https://esm.sh/react@17.0.1': Internal Server Error
INFO Download https://esm.sh/react@17.0.1
ERROR Fetch module 'https://esm.sh/react@17.0.1': Internal Server Error
INFO Download https://esm.sh/react@17.0.1
ERROR Fetch module 'https://esm.sh/react@17.0.1': Internal Server Error
error: Uncaught (in promise) TypeError: Cannot resolve module "file:///home/user/projects/test/.aleph/development/-/esm.sh/react@17.0.1.js" from "file:///home/user/projects/test/.aleph/development/-/deno.land/x/aleph@v0.3.0-alpha.20/framework/react/renderer.js".
    at file:///home/user/projects/test/.aleph/development/-/deno.land/x/aleph@v0.3.0-alpha.20/framework/react/renderer.js:1:0
      const { render } = await import(`file://${jsFile}`)
                         ^
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.20/server/app.ts:179:26)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.20/server/server.ts:202:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.20/cli/dev.ts:23:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.20/cli.ts:122:3)
```

Is this just an issue with esm.sh? Going to https://esm.sh/react@17.0.1 does indeed return a `500` and shows me:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "json: cannot unmarshal object into Go struct field NpmPackage.versions.exports of type string");
export default null;
```

**Comment by TranquilMarmot** [comment]
Also with `aleph.js` version `0.3.0-alpha.22` I get this:

```
> aleph --version
aleph.js 0.3.0-alpha.22
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2

> aleph dev      
Download https://esm.sh/postcss@8.2.8
Download https://esm.sh/terser@5.6.1?no-check
error: Uncaught (in promise) TypeError: Import 'https://esm.sh/postcss@8.2.8' failed: 500 Internal Server Error
    at https://deno.land/x/aleph@v0.3.0-alpha.22/compiler/css.ts:1:0
  const { default: cmd } = await import(`./cli/${command}.ts`)
                           ^
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.22/cli.ts:75:28)
```

... so it does seem like esm.sh is just having issues. Are there any alternatives or is the solution to just wait for it to resolve?

**Comment by KotlinIsland** [comment]
https://github.com/postui/esm.sh/issues/41

**Comment by KotlinIsland** [comment]
This is resolved now.
