### ISSUE TITLE
Dependences missed of the old alpha version

### ISSUE THREAD

**Issue by vincenzopalazzo** [alephjs/aleph.js#235]
Hello, I'm working with the old version of the aleph library because it version works for me but today it is I restart my docker container and I receive the following error 

```
lnchecker_1  | Download https://deno.land/x/aleph@v0.3.0-alpha.22/types.ts
lnchecker_1  | error: Uncaught (in promise) TypeError: Import 'https://deno.land/x/aleph@v0.3.0-alpha.22/plugins/css.ts' failed: 404 Not Found
lnchecker_1  |     at file:///lnwebapp/aleph.config.ts:1:0
lnchecker_1  |         let { default: v } = await import('file://' + p)
lnchecker_1  |                              ^
lnchecker_1  |     at async loadConfig (https://deno.land/x/aleph@v0.3.0-alpha.18/server/config.ts:37:30)
lnchecker_1  |     at async Promise.all (index 0)
lnchecker_1  |     at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.18/server/app.ts:94:33)
lnchecker_1  |     at async serve (https://deno.land/x/aleph@v0.3.0-alpha.18/server/server.ts:202:3)
lnchecker_1  |     at async default (https://deno.land/x/aleph@v0.3.0-alpha.18/cli/dev.ts:23:3)
lnchecker_1  |     at async main (https://deno.land/x/aleph@v0.3.0-alpha.18/cli.ts:122:3)

```

Do you think that cache the build would be a good idea to avoid this problem?

**Comment by ije** [comment]
alpha.23 fixed this

**Comment by ije** [comment]
oh, sorry! in alpha.22 i removed the css plugin, it supports css out of the box.

**Comment by ije** [comment]
please remove the css plugin in your aleph.config.ts 🙏

**Comment by vincenzopalazzo** [comment]
@ije  Thanks, it works but now it is broken the API action, I'm not able to make the action with the par `/api/sometings/[actions]`

**Comment by ije** [comment]
any message prints?

**Comment by vincenzopalazzo** [comment]
@ije yes the error is only 404 and the object actions is undefined with the version 23
