### ISSUE TITLE
Starter program crashes on `aleph start` with TypeError: An unsupported media type was attempted to be imported as a module

### ISSUE THREAD

**Issue by danaugrs** [alephjs/aleph.js#253]
Problem:
```
> aleph init test1
Add recommended workspace settings of VS Code? [y/n]
Saving template...
Done
---
$ cd test1
$ aleph dev     # start the app in `development` mode
$ aleph start   # start the app in `production` mode
$ aleph build   # build the app to a static site (SSG)
---
> cd test1
> aleph start
INFO Compiling...
error: Uncaught (in promise) TypeError: An unsupported media type was attempted to be imported as a module.
  Specifier: https://cdn.esm.sh/v35/fraction.js@4.0.13/deno/fraction.js.js
  MediaType: Json
  const { default: Plugin } = await import(url)
                              ^
    at async importPostcssPluginByName (https://deno.land/x/aleph@v0.3.0-alpha.25/server/css.ts:95:31)
    at async https://deno.land/x/aleph@v0.3.0-alpha.25/server/css.ts:83:14
    at async Promise.all (index 0)
    at async initPostCSS (https://deno.land/x/aleph@v0.3.0-alpha.25/server/css.ts:72:18)
    at async Promise.all (index 0)
    at async CSSProcessor.transform (https://deno.land/x/aleph@v0.3.0-alpha.25/server/css.ts:36:35)
    at async Application.precompile (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:1000:29)
    at async Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:1111:22)
    at async Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:1162:24)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:253:11)
```
aleph.js `0.3.0-alpha.25`
deno: `1.8.3 (release, x86_64-pc-windows-msvc)`
v8: `9.0.257.3`
typescript: `4.2.2`

**Comment by ije** [comment]
@danaugrs it's esm.sh bug by the latest updates, I will fix it ASAP, thanks!

**Comment by ije** [comment]
i can get it works now, pls clear the cache and try again, thanks

**Comment by danaugrs** [comment]
It works now! 🎉
