### ISSUE TITLE
TypeError with `aleph start` acorn.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#254]
aleph init default project
```
> aleph --version
aleph.js 0.3.0-alpha.25
deno 1.8.3
v8 9.0.257.3
typescript 4.2.2

> aleph start
...
error: Uncaught (in promise) TypeError: The requested module '/v35/acorn@8.1.0/deno/acorn.js' does not provide an export named 'default'
    const { minify } = await import('https://esm.sh/terser@5.6.1?no-check')
                       ^
    at async minify (https://deno.land/x/aleph@v0.3.0-alpha.25/bundler/mod.ts:305:24)
    at async Bundler._bundle (https://deno.land/x/aleph@v0.3.0-alpha.25/bundler/mod.ts:287:18)
    at async Bundler.createPolyfillBundle (https://deno.land/x/aleph@v0.3.0-alpha.25/bundler/mod.ts:213:7)
    at async Bundler.bundle (https://deno.land/x/aleph@v0.3.0-alpha.25/bundler/mod.ts:86:5)
    at async Application.bundle (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:1273:5)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.25/server/app.ts:275:7)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.25/server/server.ts:208:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.25/cli/start.ts:33:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.25/cli.ts:122:3)
```

**Comment by shadowtime2000** [comment]
cc @ije 

Seems to be a problem with esm.sh

**Comment by ije** [comment]
fixed in esm.sh **v37**, pls clear the cache and try again, thanks

**Comment by KotlinIsland** [comment]
Thanks! fixed.
