### ISSUE TITLE
Deno 1.9.1 CompileError: WebAssembly.instantiate(): BufferSource argument is empty

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#288]
```
error: Uncaught (in promise) CompileError: WebAssembly.instantiate(): BufferSource argument is empty
    const instance = await WebAssembly.instantiate(module, imports);
                                       ^
    at load (https://deno.land/x/aleph@v0.3.0-alpha.31/compiler/dist/wasm-pack.js:194:40)
    at init (https://deno.land/x/aleph@v0.3.0-alpha.31/compiler/dist/wasm-pack.js:266:38)
    at async initWasm (https://deno.land/x/aleph@v0.3.0-alpha.31/compiler/mod.ts:78:5)
    at async checkWasmReady (https://deno.land/x/aleph@v0.3.0-alpha.31/compiler/mod.ts:95:5)
    at async transform (https://deno.land/x/aleph@v0.3.0-alpha.31/compiler/mod.ts:128:3)
    at async Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.31/server/app.ts:1149:48)
    at async Application.addModule (https://deno.land/x/aleph@v0.3.0-alpha.31/server/app.ts:504:5)
    at async init (https://deno.land/x/aleph@v0.3.0-alpha.31/framework/react/init.ts:40:5)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.31/server/app.ts:204:5)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.31/server/stdserver.ts:29:3)
```

**Comment by ije** [comment]
sorry, i can't repeat this, can you please clean the cache dir and try again?

**Comment by KotlinIsland** [comment]
true

**Comment by talentlessguy** [comment]
Having the same error as well.

I have cleared the `.aleph` folder, deno cache, yet it still repeats:

```
➜ aleph dev --port 3000 -r
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
INFO load env from .env
Check https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/init.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/refresh.ts
error: Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected 5610751 bytes, fell off end @+7671
    const instance = await WebAssembly.instantiate(module, imports);
                                       ^
    at load (https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/dist/wasm-pack.js:194:40)
    at init (https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/dist/wasm-pack.js:266:38)
    at async initWasm (https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/mod.ts:80:5)
    at async checkWasmReady (https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/mod.ts:97:5)
    at async transform (https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/mod.ts:130:3)
    at async Application.transpileModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1061:62)
    at async Application.addModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:451:5)
    at async init (https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/init.ts:39:5)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:188:5)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts:29:3)
```
