### ISSUE TITLE
build throws when using custom "srcDir" but "dist" doesn't exist

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#300]
Hey, I use a custom `srcDir` and I get this error when I try to build and `dist` doesn't exist

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
await Deno.mkdir(distDir)
^
at unwrapOpResult (deno:core/core.js:99:13)
at async Object.mkdir (deno:runtime/js/30_fs.js:101:5)
at async Application.build (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:803:7)
at async default (https://deno.land/x/aleph@v0.3.0-alpha.32/cli/build.ts:18:3)
at async main (https://deno.land/x/aleph@v0.3.0-alpha.32/cli.ts:99:3)
```

My Aleph config: 

```
{
  "srcDir": "app"
}
```

However, when I create an empty `./dist`, it works

My project structure then looks like

```
dist/
app/
aleph.config.json
```

**Comment by ije** [comment]
`srcDir` option has been removed, but you still can put code in `src` directory that works as well
