### ISSUE TITLE
Can't use imports from import_map in aleph.config.ts

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#305]
The following config

```typescript
import { Config } from "aleph/types.ts";

export default {
  srcDir: "app",
  buildTarget: "es2020",
} as Config;
```

throws

```
error: Uncaught (in promise) TypeError: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Config'.
import { Config } from "aleph/types.ts";
         ~~~~~~
    at file:///.../aleph.config.ts:1:10
        let { default: v } = await import('file://' + p)
                             ^
    at async loadConfig (https://deno.land/x/aleph@v0.3.0-alpha.32/server/config.ts:53:30)
    at async Promise.all (index 0)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.32/server/app.ts:122:33)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.32/server/stdserver.ts:29:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.32/cli/dev.ts:24:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.32/cli.ts:99:3)
```

when using `aleph dev` or `aleph build`

**Comment by ije** [comment]
this is expected since the app.config.ts is imported by aleph client run in deno without import map

**Comment by hazae41** [comment]
Can't we change this behaviour?

**Comment by ije** [comment]
or we can pre transpile the app.config.js to mix import map
