### ISSUE TITLE
Getting error in pages/framework upon aleph dev command.

### ISSUE THREAD

**Issue by Ayushi1910** [alephjs/aleph.js#311]
ERROR TypeError: Is a directory (os error 21)

    at file:///SystemPath/aleph/hello-aleph/.aleph/development/pages/index.cc61d1ad7.js:5:0
    at async https://deno.land/x/aleph@v0.3.0-alpha.1/server/app.ts:1611:48
    at async Promise.all (index 0)
    at async Appliaction.renderPage (https://deno.land/x/aleph@v0.3.0-alpha.1/server/app.ts:1621:17)
    at async Appliaction.getSSRData (https://deno.land/x/aleph@v0.3.0-alpha.1/server/app.ts:209:34)
    at async Server.handle (https://deno.land/x/aleph@v0.3.0-alpha.1/server/server.ts:98:44)

**Comment by shadowtime2000** [comment]
Closing because no response regarding problem. If someone else is experiencing this issue feel free to comment here with the important information and I will open it up again.
