### ISSUE TITLE
aleph start fails to read popper.client.js when using material-ui

### ISSUE THREAD

**Issue by guidorice** [alephjs/aleph.js#317]
I noticed on my project which is including material-ui (https://esm.sh/@material-ui/core@4.11.4/), that `aleph dev` is working, but `aleph start` fails with:

```
INFO Compiling...
INFO   {} polyfills.js (ES2015) • 207KB
INFO   {} deps.js • 967KB
INFO   {} shared.js • 543B
  > .aleph/production/-/cdn.esm.sh/v41/@material-ui/core@4.11.4/deno/core.client.js:9713:15: error: Could not read from file: /home/deno/my_app/.aleph/production/-/cdn.esm.sh/v41/popper.js@1.16.1-lts/deno/popper.client.js
     9713 │ import f0 from "../../../popper.js@1.16.1-lts/deno/popper.client.js";
          ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 error: Uncaught (in promise) Error: Build failed with 1 error:
 .aleph/production/-/cdn.esm.sh/v41/@material-ui/core@4.11.4/deno/core.client.js:9713:15: error: Could not read from file: /home/deno/my_app/.aleph/production/-/cdn.esm.sh/v41/popper.js@1.16.1-lts/deno/popper.client.js
   let error = new Error(`${text}${summary}`);
               ^
     at failureErrorWithLog (https://deno.land/x/esbuild@v0.11.14/mod.js:1300:15)
     at buildResponseToResult (https://deno.land/x/esbuild@v0.11.14/mod.js:995:26)
     at https://deno.land/x/esbuild@v0.11.14/mod.js:1088:14
     at https://deno.land/x/esbuild@v0.11.14/mod.js:564:9
     at handleIncomingPacket (https://deno.land/x/esbuild@v0.11.14/mod.js:653:9)
     at readFromStdout (https://deno.land/x/esbuild@v0.11.14/mod.js:531:7)
     at https://deno.land/x/esbuild@v0.11.14/mod.js:1547:11
``
I am not sure why it's missing this popper.client.js or, what to do about it?

Also, a general question: is anyone successfully using material-ui with aleph.js so far? do all the react components work ok?

**Comment by kratoon3** [comment]
I have the same error. 
Maybe a bug in esm.sh? @ije 

In the `.aleph/production/` directory there's file called `popper.js.client.js`, not `popper.client.js`.

Simple code to reproduce:
```js
import React from 'react';
import { makeStyles } from 'https://esm.sh/@material-ui/core@4.11.4';
const useStyles = makeStyles({});
export default function Home() {
  const classes = useStyles();
  return (<div className="page"></div>);
}
```

aleph.js 0.3.0-alpha.33
deno 1.10.2
v8 9.1.269.27
typescript 4.2.2

**Comment by kratapps** [comment]
Related to https://github.com/postui/esm.sh/issues/63

**Comment by kratoon3** [comment]
Related to https://github.com/postui/esm.sh/issues/63

**Comment by ije** [comment]
> Related to [postui/esm.sh#63](https://github.com/postui/esm.sh/issues/63)

this has been fixed
