### ISSUE TITLE
Crash when importing WalletConnect

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#319]
When I import these two modules, Aleph.js crashes on compilation step, similarly to the crash when using circular imports (https://github.com/alephjs/aleph.js/issues/306)

```typescript
import WalletConnect from "https://esm.sh/@walletconnect/client"
import QRCodeModal from "https://esm.sh/@walletconnect/qrcode-modal"
```

Here is the debug 

```
> aleph dev
Check https://deno.land/x/aleph@v0.3.0-alpha.32/cli.ts
INFO Config loaded from aleph.config.ts
TIMING load config in 142ms
TIMING init framework in 181ms
TIMING apply plugins in 0ms
INFO Compiling...
TIMING init compiler wasm in 403ms
TIMING compile '/comps/app.tsx' in 429ms
TIMING compile '/comps/ethereum/connector.tsx' in 12ms
TIMING compile '/comps/ethereum/walletconnect.tsx' in 25ms
TIMING compile 'https://esm.sh/@walletconnect/client' in 2ms
TIMING compile 'https://cdn.esm.sh/v41/@walletconnect/client@1.4.1/deno/client.development.js' in 15ms
TIMING compile 'https://cdn.esm.sh/v41/@walletconnect/iso-crypto@1.4.1/deno/iso-crypto.development.js' in 33ms
TIMING compile 'https://cdn.esm.sh/v41/@pedrouid/iso-crypto@1.1.0/deno/iso-crypto.development.js' in 190ms
TIMING compile 'https://cdn.esm.sh/v41/crypto-browserify@3.12.0/deno/crypto-browserify.development.js' in 45ms
TIMING compile 'https://cdn.esm.sh/v41/browserify-sign@4.2.1/deno/browserify-sign.development.js' in 93ms
TIMING compile 'https://cdn.esm.sh/v41/create-ecdh@4.0.4/deno/create-ecdh.development.js' in 97ms
TIMING compile 'https://cdn.esm.sh/v41/diffie-hellman@5.0.3/deno/diffie-hellman.development.js' in 85ms
TIMING compile 'https://cdn.esm.sh/v41/miller-rabin@4.0.1/deno/miller-rabin.development.js' in 20ms
TIMING compile 'https://cdn.esm.sh/v41/brorand@1.1.0/deno/brorand.development.js' in 17ms
TIMING compile 'https://cdn.esm.sh/v41/elliptic@6.5.4/deno/elliptic.development.js' in 511ms
>
```

**Comment by ije** [comment]
please try alpha.33 that fixs #306

**Comment by hazae41** [comment]
Yes! It's fixed

Thanks

**Comment by hazae41** [comment]
I have another problem now

```
21:52:23.955 | > app/.aleph/production/-/cdn.esm.sh/v41/hmac-drbg@1.0.1/deno/hmac-drbg.js:2:23: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/hash.js@1.1.7/deno/hash.js
21:52:23.956 | 2 │ import __hash_js$ from "../../hash.js@1.1.7/deno/hash.js";
21:52:23.956 | ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.956 | > app/.aleph/production/-/cdn.esm.sh/v41/create-hash@1.2.0/deno/create-hash.js:3:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/md5.js@1.3.5/deno/md5.js
21:52:23.957 | 3 │ import __md5_js$ from "../../md5.js@1.3.5/deno/md5.js";
21:52:23.957 | ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.957 | > app/.aleph/production/-/cdn.esm.sh/v41/create-hash@1.2.0/deno/create-hash.js:2:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/sha.js@2.4.11/deno/sha.js
21:52:23.958 | 2 │ import __sha_js$ from "../../sha.js@2.4.11/deno/sha.js";
21:52:23.958 | ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.969 | > app/.aleph/production/-/cdn.esm.sh/v41/public-encrypt@4.0.3/deno/public-encrypt.js:3:21: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/bn.js@4.12.0/deno/bn.js
21:52:23.969 | 3 │ import __bn_js$ from "../../bn.js@4.12.0/deno/bn.js";
21:52:23.969 | ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.970 | > app/.aleph/production/-/cdn.esm.sh/v41/browserify-rsa@4.1.0/deno/browserify-rsa.js:2:21: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/bn.js@5.2.0/deno/bn.js
21:52:23.970 | 2 │ import __bn_js$ from "../../bn.js@5.2.0/deno/bn.js";
21:52:23.970 | ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.972 | > app/.aleph/production/-/cdn.esm.sh/v41/browserify-des@1.0.2/deno/browserify-des.js:4:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/des.js@1.0.1/deno/des.js
21:52:23.972 | 4 │ import __des_js$ from "../../des.js@1.0.1/deno/des.js";
21:52:23.972 | ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:23.988 | > app/.aleph/production/-/cdn.esm.sh/v41/parse-asn1@5.1.6/deno/parse-asn1.js:2:23: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/asn1.js@5.4.1/deno/asn1.js
21:52:23.988 | 2 │ import __asn1_js$ from "../../asn1.js@5.4.1/deno/asn1.js";
21:52:23.988 | ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:24.017 | > app/.aleph/production/-/cdn.esm.sh/v41/@walletconnect/utils@1.4.1/deno/utils.js:6:21: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/bn.js@4.11.8/deno/bn.js
21:52:24.017 | 6 │ import __bn_js$ from "../../../bn.js@4.11.8/deno/bn.js";
21:52:24.017 | ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
21:52:24.104 | error: Uncaught (in promise) Error: Build failed with 8 errors:
21:52:24.104 | app/.aleph/production/-/cdn.esm.sh/v41/@walletconnect/utils@1.4.1/deno/utils.js:6:21: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/bn.js@4.11.8/deno/bn.js
21:52:24.106 | app/.aleph/production/-/cdn.esm.sh/v41/browserify-des@1.0.2/deno/browserify-des.js:4:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/des.js@1.0.1/deno/des.js
21:52:24.106 | app/.aleph/production/-/cdn.esm.sh/v41/browserify-rsa@4.1.0/deno/browserify-rsa.js:2:21: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/bn.js@5.2.0/deno/bn.js
21:52:24.106 | app/.aleph/production/-/cdn.esm.sh/v41/create-hash@1.2.0/deno/create-hash.js:2:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/sha.js@2.4.11/deno/sha.js
21:52:24.106 | app/.aleph/production/-/cdn.esm.sh/v41/create-hash@1.2.0/deno/create-hash.js:3:22: error: Could not read from file: /vercel/path2/app/.aleph/production/-/cdn.esm.sh/v41/md5.js@1.3.5/deno/md5.js
21:52:24.106 | ...
21:52:24.106 | let error = new Error(`${text}${summary}`);
21:52:24.106 | ^
21:52:24.106 | at failureErrorWithLog (https://deno.land/x/esbuild@v0.11.22/mod.js:1406:15)
21:52:24.107 | at https://deno.land/x/esbuild@v0.11.22/mod.js:1088:28
21:52:24.107 | at runOnEndCallbacks (https://deno.land/x/esbuild@v0.11.22/mod.js:876:63)
21:52:24.107 | at buildResponseToResult (https://deno.land/x/esbuild@v0.11.22/mod.js:1086:7)
21:52:24.107 | at https://deno.land/x/esbuild@v0.11.22/mod.js:1193:14
21:52:24.107 | at https://deno.land/x/esbuild@v0.11.22/mod.js:567:9
21:52:24.107 | at handleIncomingPacket (https://deno.land/x/esbuild@v0.11.22/mod.js:664:9)
21:52:24.107 | at readFromStdout (https://deno.land/x/esbuild@v0.11.22/mod.js:534:7)
21:52:24.107 | at https://deno.land/x/esbuild@v0.11.22/mod.js:1676:11
21:52:24.125 | Error: Command "curl -fsSL https://deno.land/x/install/install.sh \| sh -s v1.10.1 && /vercel/.deno/bin/deno run -A https://deno.land/x/aleph/cli.ts build app" exited with 1
```

**Comment by ije** [comment]
@hazae41 I'm wondering in 0.3 beta still has this problem?
