### ISSUE TITLE
Support import_map.json in aleph.config.ts

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#323]
Currently, it is not possible to use import_map.json with aleph.config.ts.

It results in an error like the following:
```
Check file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts
error: Uncaught (in promise) TypeError: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Config'.
import type { Config } from 'aleph/types'
              ~~~~~~
    at file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'config'.
import { config } from "dotenv";
         ~~~~~~
    at file:///home/noverby/Work/radikal/radikalwiki-aleph/aleph.config.ts:2:10

Found 2 errors.
        let { default: v } = await import('file://' + p)
                             ^
    at async loadConfig (https://deno.land/x/aleph@v0.3.0-alpha.33/server/config.ts:58:30)
    at async Promise.all (index 0)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:99:33)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts:29:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts:24:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts:100:3)
```

It would be neat if we could add support for it.

**Comment by ije** [comment]
@noverby will support this in beta.1
