### ISSUE TITLE
Fails to build with pages requesting API functions

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/aleph.js#337]
For example I have this page:

```js
import { useRouter, useDeno } from 'aleph/framework/react/hooks.ts'
import React from 'react'

export default function Home() {
  const { params } = useRouter()

  const { address, coin } = params

  const { data } = useDeno(async () => {
    const res = await fetch(`http://localhost:3000/api/func`)
    const json = await res.json()

    return json
  })

  return <div></div>
}
```

this is what happens when running `aleph build`:

```
➜ aleph build
INFO load env from .env
INFO - Pages (SSG)
INFO   ○ / • 9KB
error: Uncaught (in promise) TypeError: error sending request for url (http://localhost:3000/api/wallet?coin=eth&address=0xD3B282e9880cDcB1142830731cD83f7ac0e1043f): error trying to connect: tcp connect error: Connection refused (os error 111)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async mainFetch (deno:extensions/fetch/26_fetch.js:229:14)
```

## info

```
➜ aleph --version
aleph.js 0.3.0-alpha.33
deno 1.11.0
v8 9.1.269.35
typescript 4.3.2
```

**Comment by ije** [comment]
currently in ssg mode, the APIs code will be dropped, try `start` mode. next we will support apis in vercel and deno deploy

**Comment by talentlessguy** [comment]
@ije so `build` only support SSG?

**Comment by shadowtime2000** [comment]
Yes. `build` is for SSG.

**Comment by talentlessguy** [comment]
got it, then closing it
