### ISSUE TITLE
The SASS module doesn't seem to work

### ISSUE THREAD

**Issue by Hunam6** [alephjs/aleph.js#34]
That's my config file:
```js
import sass from 'https://deno.land/x/aleph@v0.2.25/plugins/sass.ts'
export default {
  plugins: [sass]
}
```
It returns an error:
```
error: Uncaught (in promise) TypeError: renderSync is not a function
        const ret = renderSync({
                    ^
    at Object.transform (sass.ts:8:21)
    at Project._compile (project.ts:991:66)
    at async Project._compile (project.ts:1127:28)
    at async Project._init (project.ts:627:25)
    at async project.ts:106:13
    at async start (server.ts:12:5)
```

**Comment by ije** [comment]
@Hunam6 sorry, this is bug, I've fixed, will release it later.

**Comment by ije** [comment]
@Hunam6 i just released a fix patch, please update the `aleph` command:

```bash
aleph upgrade
```
