### ISSUE TITLE
Scoped npm package support

### ISSUE THREAD

**Issue by guiguan** [alephjs/aleph.js#341]
tried `aleph dev -r` with following `import_map.json`:

```json
{
  "imports": {
    "~/": "./",
    "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.33/",
    "aleph/types": "https://deno.land/x/aleph@v0.3.0-alpha.33/types.ts",
    "framework": "https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/mod.ts",
    "framework/react": "https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/mod.ts",
    "react": "https://esm.sh/react@17.0.2",
    "react-dom": "https://esm.sh/react-dom@17.0.2",
    "@chakra-ui/react": "https://esm.sh/@chakra-ui/react@1.6.4",
    "@chakra-ui/icons": "https://esm.sh/@chakra-ui/icons@1.0.13",
    "@emotion/react": "https://esm.sh/@emotion/react@11.4.0",
    "@emotion/styled": "https://esm.sh/@emotion/styled@11.3.0",
    "framer-motion": "https://esm.sh/framer-motion@4.1.17"
  },
  "scopes": {}
}
```

then got:

```zsh
❯ aleph dev -r
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/init.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/refresh.ts
INFO Download https://esm.sh/react-refresh@0.10.0/runtime?dev
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/util.ts
INFO Download https://cdn.esm.sh/v43/react-refresh@0.10.0/deno/runtime.development.js
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/renderer.ts
INFO Download https://esm.sh/react@11.4.0?dev
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/events.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/components/ErrorBoundary.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/context.ts
INFO Download https://esm.sh/react-dom@11.4.0/server?dev
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/helper.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/hooks.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/pageprops.ts
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/routing.ts
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/redirect.ts
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react@11.4.0?dev failed, retrying...
WARN Download https://esm.sh/react-dom@11.4.0/server?dev failed, retrying...
ERROR Load module 'https://esm.sh/react@11.4.0': Internal Server Error
error: Uncaught (in promise) Error: Internal Server Error
        err = new Error(resp.statusText)
              ^
    at cache (https://deno.land/x/aleph@v0.3.0-alpha.33/server/cache.ts:51:15)
    at async Application.fetch (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:830:12)
    at async Application.loadModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:886:22)
    at async Application.initModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1021:51)
    at async https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1169:27
    at async Promise.all (index 0)
    at async Application.transpileModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1167:7)
    at async Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:918:5)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:192:19)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts:29:3)
```

somehow, the scoped npm package `@emotion/react` version is messed up with `react` and `react-dom`

**Comment by ije** [comment]
thanks, i just figure out what happend, to respect react version in import maps, i added a logic in https://github.com/alephjs/aleph.js/blob/master/server/config.ts#L213 that got wrong react version, i will fix it at next release, pls try to move `react` after `@emotion/react`

**Comment by guiguan** [comment]
cool, cherrypicked your change in 136330698b10c37990b104118fa0af9651815e51 to v0.3.0-alpha.33, and then it works! Thank you
