### ISSUE TITLE
404 for dependancy during build

### ISSUE THREAD

**Issue by Lite5h4dow** [alephjs/aleph.js#354]
static building my site fails in my pipeline because a dependency is unavailable and 404'ing
```
...
Download https://deno.land/std@0.62.0/path/_globrex.ts
Download https://deno.land/std@0.62.0/node/_util/_util_promisify.ts
Download https://deno.land/std@0.62.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.62.0/node/_util/_util_types.ts
Download https://deno.land/std@0.62.0/node/_utils.ts
Download https://deno.land/std@0.62.0/bytes/mod.ts
Download https://cdn.esm.sh/v44/postcss@8.2.12/lib/previous-map.d.ts
error: Uncaught (in promise) TypeError: Import 'https://cdn.esm.sh/v44/webidl-conversions@4.0.2/deno/webidl-conversions.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v44/whatwg-url@7.1.0/deno/whatwg-url.js:1:0
  const { default: cmd } = await import(`./cli/${command}.ts`)
                           ^
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts:74:28)
Error: Process completed with exit code 1.
```
i cant build and deploy my website till this is fixed however I am unsure as to if this is an issue with aleph's build or the cdn.

**Comment by ije** [comment]
thanks, i just updated esm.sh that has an issue to transpile cjs code, will fix this ASAP!

**Comment by ije** [comment]
just updated esm.sh cjs-module-lexer server, pls try again
