### ISSUE TITLE
TS2416 Error starting new project on deno 1.13.0 + alpha.33

### ISSUE THREAD

**Issue by chasestubblefield** [alephjs/aleph.js#357]
## Environment
* MacOS 11.4
* deno 1.13.0 (installed with Homebrew)

## Steps to reproduce
* Empty deno cache (`~/Library/Caches/deno`)
* Empty deno installation root (`~/.deno`)
* Install `aleph@v0.3.0-alpha.33` via `install.ts`
* Initialize new app via `aleph init`
* Run `aleph dev` in created directory

## Result
Following error occurs during `aleph init` (command still succeeds), but crashes `aleph dev`:
```
error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.62.0/io/bufio.ts:26:3
```

## Speculation
I'm very new to deno, but I think the problem is a nested dependency on `std@0.62.0`, rather than `std@0.96.0`. It looks like this dependency is coming from `esbuild@v0.11.22`, which depends on `compress@v0.3.3`, which depends on `std@0.62.0`:
```
$ deno info https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
...
│ │ │ ├─┬ https://deno.land/x/esbuild@v0.11.22/mod.js (61.03KB)
│ │ │ │ ├── https://deno.land/x/esbuild@v0.11.22/mod.d.ts (10.24KB)
│ │ │ │ └─┬ https://deno.land/x/compress@v0.3.3/mod.ts (372B)
│ │ │ │   ├─┬ https://deno.land/x/compress@v0.3.3/gzip/mod.ts (144B)
│ │ │ │   │ ├─┬ https://deno.land/x/compress@v0.3.3/gzip/gzip.ts (6.64KB)
│ │ │ │   │ │ ├─┬ https://deno.land/x/compress@v0.3.3/deps.ts (446B)
│ │ │ │   │ │ │ ├─┬ https://deno.land/std@0.62.0/archive/tar.ts (15.05KB)
...
```

## Transcript
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
$ deno --version
deno 1.13.0 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
$ deno info
DENO_DIR location: "/Users/chase/Library/Caches/deno"
Remote modules cache: "/Users/chase/Library/Caches/deno/deps"
Emitted modules cache: "/Users/chase/Library/Caches/deno/gen"
Language server registries cache: "/Users/chase/Library/Caches/deno/registries"
Origin storage: "/Users/chase/Library/Caches/deno/location_data"
$ rm -rf ~/Library/Caches/deno/
$ rm -rf ~/.deno/
$ deno run -A https://deno.land/x/aleph@v0.3.0-alpha.33/install.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/install.ts
Download https://deno.land/std@0.96.0/flags/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/cli/upgrade.ts
Download https://deno.land/std@0.96.0/_util/assert.ts
Download https://deno.land/std@0.96.0/fmt/colors.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/version.ts
Download https://deno.land/std@0.96.0/fs/exists.ts
Download https://deno.land/std@0.96.0/path/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/constants.ts
Download https://deno.land/std@0.96.0/path/separator.ts
Download https://deno.land/std@0.96.0/path/win32.ts
Download https://deno.land/std@0.96.0/path/common.ts
Download https://deno.land/std@0.96.0/path/glob.ts
Download https://deno.land/std@0.96.0/_util/os.ts
Download https://deno.land/std@0.96.0/path/_interface.ts
Download https://deno.land/std@0.96.0/path/posix.ts
Download https://deno.land/std@0.96.0/path/_util.ts
Download https://deno.land/std@0.96.0/path/_constants.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/install.ts
Looking up latest version...
Download https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/log.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/fs.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/util.ts
Download https://deno.land/std@0.96.0/fs/ensure_dir.ts
Download https://deno.land/std@0.96.0/fs/_util.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
Aleph.js was installed successfully
Run 'aleph -h' to get started
$ type aleph
aleph is /Users/chase/.deno/bin/aleph
$ aleph init aleph-demo
Download https://deno.land/x/aleph@v0.3.0-alpha.33/cli/init.ts
Download https://deno.land/x/denoflate@1.2.1/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/compress.ts
Download https://deno.land/std@0.96.0/archive/tar.ts
Download https://deno.land/x/denoflate@1.2.1/pkg/denoflate_bg.wasm.js
Download https://deno.land/x/denoflate@1.2.1/pkg/denoflate.js
Download https://deno.land/x/aleph@v0.3.0-alpha.33/types.ts
Download https://deno.land/std@0.96.0/io/util.ts
Download https://deno.land/std@0.96.0/io/readers.ts
Download https://deno.land/std@0.96.0/io/buffer.ts
Download https://deno.land/std@0.96.0/io/bufio.ts
Download https://deno.land/std@0.96.0/mime/multipart.ts
Download https://deno.land/std@0.96.0/http/http_status.ts
Download https://esm.sh/postcss@8.2.12
Download https://deno.land/std@0.96.0/bytes/mod.ts
Download https://deno.land/std@0.96.0/testing/asserts.ts
Download https://deno.land/std@0.96.0/io/ioutil.ts
Download https://deno.land/std@0.96.0/textproto/mod.ts
Download https://deno.land/std@0.96.0/_util/has_own_property.ts
Download https://deno.land/std@0.96.0/bytes/bytes_list.ts
Download https://deno.land/std@0.96.0/testing/_diff.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/deno/postcss.js
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/postcss.d.ts
Download https://cdn.esm.sh/v45/url@0.11.0/deno/url.js
Download https://cdn.esm.sh/v45/source-map@0.6.1/deno/source-map.js
Download https://cdn.esm.sh/v45/colorette@1.3.0/deno/colorette.js
Download https://cdn.esm.sh/v45/node_buffer.js
Download https://cdn.esm.sh/v45/deno_std_node_fs.js
Download https://cdn.esm.sh/v45/nanoid@3.1.23/deno/non-secure.js
Download https://cdn.esm.sh/v45/path-browserify@1.0.1/deno/path-browserify.js
Download https://cdn.esm.sh/v45/node_process.js
Download https://cdn.esm.sh/v45/querystring-es3@0.2.1/deno/querystring-es3.js
Download https://cdn.esm.sh/v45/punycode@2.1.1/deno/punycode.js
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/node.d.ts
Download https://cdn.esm.sh/v45/source-map@0.6.1/source-map.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/list.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/at-rule.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/processor.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/container.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/root.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/result.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/input.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/declaration.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/lazy-result.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/comment.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/warning.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/rule.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/css-syntax-error.d.ts
Download https://cdn.esm.sh/v45/postcss@8.2.12/lib/previous-map.d.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli/init.ts
Add recommended workspace settings of VS Code? [y/n] y
Downloading template...
Saving template...
Check https://deno.land/x/aleph@v0.3.0-alpha.33/types.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/redirect.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/events.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/hooks.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/components/Fallback.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/hoc.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/context.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/helper.ts
Download https://esm.sh/react@17.0.2
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/routing.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/renderer.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/ssr.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/pageprops.ts
Download https://esm.sh/react-dom@17.0.2/server
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/components/ErrorBoundary.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/module.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts
Download https://cdn.esm.sh/v45/react@17.0.2/deno/react.js
Download https://cdn.esm.sh/v45/@types/react@17.0.16/index.d.ts
Download https://deno.land/std@0.96.0/hash/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/config.ts
Download https://deno.land/std@0.96.0/fs/walk.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/cache.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/mime.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/bundler/mod.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/helper.ts
Download https://cdn.esm.sh/v45/react-dom@17.0.2/deno/server.js
Download https://cdn.esm.sh/v45/@types/react-dom@17.0.2/server.d.ts
Download https://deno.land/std@0.96.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.96.0/hash/hasher.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/dist/wasm-checksum.js
Download https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/dist/wasm-pack.js
Download https://deno.land/x/aleph@v0.3.0-alpha.33/compiler/dist/wasm.js
Download https://deno.land/x/aleph@v0.3.0-alpha.33/plugins/css.ts
Download https://cdn.esm.sh/v45/object-assign@4.1.1/deno/object-assign.js
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/localproxy.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/bundler/esbuild.ts
Download https://deno.land/std@0.96.0/encoding/base64.ts
Download https://deno.land/std@0.96.0/encoding/hex.ts
Download https://deno.land/std@0.96.0/hash/_wasm/wasm.js
Download https://cdn.esm.sh/v45/@types/scheduler@0.16.2/tracing.d.ts
Download https://cdn.esm.sh/v45/@types/prop-types@15.7.4/index.d.ts
Download https://cdn.esm.sh/v45/@types/react@17.0.16/global.d.ts
Download https://cdn.esm.sh/v45/csstype@3.0.8/index.d.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/api.ts
Download https://deno.land/std@0.96.0/http/server.ts
Download https://deno.land/x/esbuild@v0.11.22/mod.js
Download https://deno.land/x/esbuild@v0.11.22/mod.d.ts
Download https://deno.land/std@0.96.0/async/mod.ts
Download https://deno.land/std@0.96.0/http/_io.ts
Download https://deno.land/x/compress@v0.3.3/mod.ts
Download https://deno.land/std@0.96.0/async/deferred.ts
Download https://deno.land/std@0.96.0/async/delay.ts
Download https://deno.land/std@0.96.0/async/pool.ts
Download https://deno.land/std@0.96.0/async/mux_async_iterator.ts
Download https://deno.land/x/brotli@v0.1.4/mod.ts
Download https://deno.land/x/compress@v0.3.3/tgz/mod.ts
Download https://deno.land/x/compress@v0.3.3/tar/mod.ts
Download https://deno.land/x/compress@v0.3.3/gzip/mod.ts
Download https://deno.land/x/compress@v0.3.3/zlib/mod.ts
Download https://deno.land/x/brotli@v0.1.4/wasm.js
Download https://deno.land/x/compress@v0.3.3/interface.ts
Download https://deno.land/x/compress@v0.3.3/deps.ts
Download https://deno.land/x/compress@v0.3.3/zlib/deflate.ts
Download https://deno.land/x/compress@v0.3.3/zlib/inflate.ts
Download https://deno.land/x/compress@v0.3.3/gzip/gzip_stream.ts
Download https://deno.land/x/compress@v0.3.3/gzip/gzip_file.ts
Download https://deno.land/x/compress@v0.3.3/gzip/gzip.ts
Download https://deno.land/std@0.62.0/fs/ensure_file.ts
Download https://deno.land/x/crc32@v0.2.0/mod.ts
Download https://deno.land/std@0.62.0/archive/tar.ts
Download https://deno.land/std@0.62.0/fs/ensure_dir.ts
Download https://deno.land/std@0.62.0/path/mod.ts
Download https://deno.land/std@0.62.0/node/events.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/messages.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/deflate.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/status.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/zstream.ts
Download https://deno.land/x/compress@v0.3.3/utils/uint8.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/gzheader.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/inflate.ts
Download https://deno.land/x/compress@v0.3.3/gzip/writer_gunzip.ts
Download https://deno.land/x/compress@v0.3.3/gzip/writer_gzip.ts
Download https://deno.land/x/lz4@v0.1.2/mod.ts
Download https://deno.land/std@0.62.0/fs/_util.ts
Download https://deno.land/std@0.62.0/io/readers.ts
Download https://deno.land/std@0.62.0/io/bufio.ts
Download https://deno.land/std@0.62.0/_util/assert.ts
Download https://deno.land/std@0.62.0/path/_constants.ts
Download https://deno.land/std@0.62.0/path/glob.ts
Download https://deno.land/std@0.62.0/path/common.ts
Download https://deno.land/std@0.62.0/path/posix.ts
Download https://deno.land/std@0.62.0/path/_interface.ts
Download https://deno.land/std@0.62.0/path/separator.ts
Download https://deno.land/std@0.62.0/path/win32.ts
Download https://deno.land/std@0.62.0/node/util.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/crc32.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/trees.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/adler32.ts
Download https://deno.land/x/lz4@v0.1.2/wasm.js
Download https://deno.land/std@0.62.0/encoding/utf8.ts
Download https://deno.land/std@0.62.0/path/_globrex.ts
Download https://deno.land/std@0.62.0/path/_util.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/inftrees.ts
Download https://deno.land/x/compress@v0.3.3/zlib/zlib/inffast.ts
Download https://deno.land/std@0.62.0/bytes/mod.ts
Download https://deno.land/std@0.62.0/node/_util/_util_callbackify.ts
Download https://deno.land/std@0.62.0/node/_utils.ts
Download https://deno.land/std@0.62.0/node/_util/_util_types.ts
Download https://deno.land/std@0.62.0/node/_util/_util_promisify.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/mod.ts
error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.62.0/io/bufio.ts:26:3
Done
---
Aleph.js is ready to go!
$ cd aleph-demo
$ aleph dev     # start the app in `development` mode
$ aleph start   # start the app in `production` mode
$ aleph build   # build the app to a static site (SSG)
---
$ cd aleph-demo/
$ aleph dev
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/shared/flags.ts
Download https://deno.land/x/aleph@v0.3.0-alpha.33/server/server.ts
Download https://deno.land/std@0.96.0/ws/mod.ts
Download https://deno.land/std@0.96.0/hash/sha1.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
error: Uncaught (in promise) TypeError: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.62.0/io/bufio.ts:26:3
  const { default: cmd } = await import(`./cli/${command}.ts`)
                           ^
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts:74:28)
```

**Comment by chasestubblefield** [comment]
Apologies, deno 1.13.1 just released yesterday, and after upgrading and going through these same steps, no errors. No problem with aleph it seems. However that internal dependency on an old standard library seems like it could cause problems, but again, I'm new to deno so feel free to disregard. Cheers, can't wait to play with aleph!
