### ISSUE TITLE
Inline style missed

### ISSUE THREAD

**Issue by vincenzopalazzo** [alephjs/aleph.js#358]
With the new version of aleph.js I receive the following error, any idea?

```
➜  ln-sanitycheck git:(main) aleph dev
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/cli/dev.ts
INFO Config loaded from aleph.config.ts
Check https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/init.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/bootstrap.ts
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/framework/core/hmr.ts
ERROR Load module '#inline-style-3yGu5s32KOZcWZ6aYAq1cIVW1Q': No such file
error: Uncaught (in promise) Error: No such file
        return Promise.reject(new Error(`No such file`))
                              ^
    at Application.fetch (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:816:31)
    at async Application.loadModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:886:22)
    at async Application.initModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1021:51)
    at async https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1169:27
    at async Promise.all (index 3)
    at async Application.transpileModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1167:7)
    at async Application.compile (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:918:5)
    at async Promise.all (index 3)
    at async Application.init (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:256:5)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.33/server/stdserver.ts:29:3)
```

**Comment by ije** [comment]
can not repeat this in beta.2
