### ISSUE TITLE
error: Uncaught (in promise) TypeError: TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.

### ISSUE THREAD

**Issue by Lite5h4dow** [alephjs/aleph.js#391]
```
error: Uncaught (in promise) TypeError: TS2801 [ERROR]: This condition will always return true since this 'Promise<boolean>' is always defined.
    if (existsFile(path)) {
        ~~~~~~~~~~~~~~~~
    at https://deno.land/x/aleph@v0.3.0-beta.12/server/aleph.ts:941:9

TS2773 [ERROR]:     Did you forget to use 'await'?
        if (existsFile(path)) {
            ~~~~~~~~~~~~~~~~
        at https://deno.land/x/aleph@v0.3.0-beta.12/server/aleph.ts:941:9
  const { default: cmd, helpMessage: cmdHelpMessage } = await import(`./commands/${command}.ts`)
                                                        ^
    at async main (https://deno.land/x/aleph@v0.3.0-beta.12/cli.ts:64:57)
```

**Comment by ije** [comment]
i will release the bugfix later, thanks 🙏

**Comment by ije** [comment]
fixed in beta.13, pls upgrade

**Comment by kotx** [comment]
Hi, thanks for fixing this issue!
Seems like there are still some issues with beta.13 though. I'm getting 177 errors when initializing a new project. They all look something like this:
```
TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'text' must be of type 'SVGProps<SVGTextElement>', but here has type 'SVGProps<SVGTextElement>'.
            text: React.SVGProps<SVGTextElement>;
            ~~~~
    at https://cdn.esm.sh/v52/@types/react@17.0.21/index.d.ts:3276:13

    'text' was also declared here.
                text: React.SVGProps<SVGTextElement>;
                ~~~~
        at https://cdn.esm.sh/v48/@types/react@17.0.20/index.d.ts:3277:13
```
