### ISSUE TITLE
incompatible with formik

### ISSUE THREAD

**Issue by dfang** [alephjs/aleph.js#396]
with this [example code](https://formik.org/docs/examples/basic), i got this error

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2020,mode=imports/optimized/react.js:186:13)
    at exports.useRef (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2020,mode=imports/optimized/react.js:291:12)
    at useFormik (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.skypack.dev/-/formik@v2.2.9-nqjqYdVR1Zrz0pAQpnm3/dist=es2020,mode=imports/optimized/formik.js:1195:23)
    at Formik (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.skypack.dev/-/formik@v2.2.9-nqjqYdVR1Zrz0pAQpnm3/dist=es2020,mode=imports/optimized/formik.js:1762:19)
    at processChild (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.esm.sh/v52/react-dom@17.0.2/deno/server.development.js:2599:22)
    at resolve (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.esm.sh/v52/react-dom@17.0.2/deno/server.development.js:2531:13)
    at ReactDOMServerRenderer2.render (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.esm.sh/v52/react-dom@17.0.2/deno/server.development.js:2890:30)
    at ReactDOMServerRenderer2.read (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.esm.sh/v52/react-dom@17.0.2/deno/server.development.js:2837:37)
    at renderToString2 (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/cdn.esm.sh/v52/react-dom@17.0.2/deno/server.development.js:3286:35)
    at Object.render (file:///Users/mj/Code/deno_next_links/deno_next_links/.aleph/development/-/deno.land/x/aleph@v0.3.0-beta.14/framework/react/renderer.js#be2000:84:18)
```

**Comment by dfang** [comment]
```
{
  "imports": {
    "~/": "./",
    "aleph/": "https://deno.land/x/aleph@v0.3.0-beta.14/",
    "aleph/types": "https://deno.land/x/aleph@v0.3.0-beta.14/types.d.ts",
    "aleph/web": "https://deno.land/x/aleph@v0.3.0-beta.14/framework/core/mod.ts",
    "aleph/react": "https://deno.land/x/aleph@v0.3.0-beta.14/framework/react/mod.ts",
    "react": "https://esm.sh/react@17.0.2",
    "react-dom": "https://esm.sh/react-dom@17.0.2",
    "formik":"https://cdn.skypack.dev/formik",
    "yup":"https://cdn.skypack.dev/yup"
  },
  "scopes": {}
}
```

it works if i change `https://cdn.skypack.dev/formik` to `https://esm.sh/formik` and `https://cdn.skypack.dev/yup` to `https://esm.sh/yup `

**Comment by ije** [comment]
because aleph is using esm.sh version of react, but https://cdn.skypack.dev/formik depends on react from skypack

**Comment by talentlessguy** [comment]
should this be closed? if esm.sh works then problem can be considered as solved
