### ISSUE TITLE
Bundler attemps incorrect download link when running in production

### ISSUE THREAD

**Issue by tiptenbrink** [alephjs/aleph.js#418]
```javascript
❯ aleph start
INFO Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
WARN Download https://deno.land/x/zod@v3.9.8/index.ts/external.ts failed, retrying...
error: Uncaught (in promise) Error: Can't compile module '/pages/index.tsx': Can't compile module '/components/deployContent.tsx': Can't compile module '/components/deployable.tsx': Can't compile module '/lib/runInfo.ts': Can't compile module '/api/deploy/runs.ts': Can't compile module 'https://deno.land/x/zod@v3.9.8/mod.ts': Not Found
  /** create bundle chunk. */
  ^
    at Bundler.compile (https://deno.land/x/aleph@v0.3.0-beta.19/bundler/mod.ts:245:3)
    at async https://deno.land/x/aleph@v0.3.0-beta.19/bundler/mod.ts:301:23
    at async Promise.all (index 0)
    at async Bundler.bundleChunk (https://deno.land/x/aleph@v0.3.0-beta.19/bundler/mod.ts:292:26)
    at async Bundler.bundle (https://deno.land/x/aleph@v0.3.0-beta.19/bundler/mod.ts:136:11)
    at async Aleph.#bundle (https://deno.land/x/aleph@v0.3.0-beta.19/server/aleph.ts:1488:5)
    at async Aleph.#init (https://deno.land/x/aleph@v0.3.0-beta.19/server/aleph.ts:262:7)
    at async serve (https://deno.land/x/aleph@v0.3.0-beta.19/server/server.ts:355:3)
    at async https://deno.land/x/aleph@v0.3.0-beta.19/commands/start.ts:45:2
```

This is an error in my current [project](https://github.com/tiptenbrink/statusdeploy/blob/a21402879b086d67eae2cbdf6c0087f90c0dfd53/sd/api/deploy/runs.ts).

**This only happens when running in production mode**, not when using `aleph dev`. It seems like it incorrectly generated the URL to download, because if you look at the index.ts it is simply importing external.ts, there is no such thing as a index.ts directory in the module.

I'm quite sure my imports are fine:

`runs.ts`:

```typescript
import { z } from 'zod'
```

`import_map.json`

```
{
  "imports": {
    "~/": "./",
    "aleph/": "https://deno.land/x/aleph@v0.3.0-beta.19/",
    "aleph/types": "https://deno.land/x/aleph@v0.3.0-beta.19/types.d.ts",
    "aleph/web": "https://deno.land/x/aleph@v0.3.0-beta.19/framework/core/mod.ts",
    "aleph/react": "https://deno.land/x/aleph@v0.3.0-beta.19/framework/react/mod.ts",
    "react": "https://esm.sh/react@17.0.2",
    "react-dom": "https://esm.sh/react-dom@17.0.2",
    "base64url": "https://deno.land/std@0.110.0/encoding/base64url.ts",
    "path": "https://deno.land/std@0.110.0/path/mod.ts",
    "octokitRequest": "https://cdn.skypack.dev/@octokit/request@5.6.2",
    "zod": "https://deno.land/x/zod@v3.9.8/mod.ts"
  },
  "scopes": {}
}
```

**Comment by ije** [comment]
@tiptenbrink thanks, i will look into it

**Comment by hiraginoyuki** [comment]
I was concerned about the same issue, so I tried to find the cause.
And I think these lines are suspicious (although I'm not sure): https://github.com/alephjs/aleph.js/blob/93ff6f078e3c5f54db6082452e1da12cf7b02026/bundler/mod.ts#L173-L181
I will do further investigations.
