### ISSUE TITLE
Getting started error 

### ISSUE THREAD

**Issue by kuhlaid** [alephjs/aleph.js#497]
When running the Getting started command `deno run -A https://deno.land/x/aleph@1.0.0-alpha.88/init.ts --template react` (from https://github.com/alephjs/aleph.js/blob/main/README.md) I get the error 

```
error: TS2339 [ERROR]: Property 'json' does not exist on type 'typeof Response'.
    return Response.json(v, { headers });
                    ~~~~
    at https://deno.land/x/aleph@1.0.0-alpha.88/server/helpers.ts:131:21

TS2339 [ERROR]: Property 'json' does not exist on type 'typeof Response'.
    return Response.json({ redirect: { location: res.headers.get("Location"), status: res.status } }, {
                    ~~~~
    at https://deno.land/x/aleph@1.0.0-alpha.88/server/helpers.ts:141:21
```

**Comment by kuhlaid** [comment]
Required deno update. After deno update the error resolved.
