### ISSUE TITLE
deno deploy error

### ISSUE THREAD

**Issue by zhenfeng-zhu** [alephjs/aleph.js#513]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/6822558/196876032-f559167d-4a96-4b62-aa85-0c8a593ec1c7.png">

TypeError: Can not modify env vars during execution.
    at Object.setEnv [as set] (deno:deploy/js/10_env.js:11:11)
    at serve (https://deno.land/x/aleph@1.0.0-beta.20/server/mod.ts:375:14)
    at serve (https://deno.land/x/aleph@1.0.0-beta.20/runtime/react/server.ts:33:5)
    at file:///src/server.ts:4:1

**Comment by ije** [comment]
fixed in beta-21, thanks!
