### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'port')

### ISSUE THREAD

**Issue by liwei511** [alephjs/aleph.js#518]
bogon:deno-react didi$ deno task dev
Task dev deno run -A dev.ts
Initialized aleph-compiler WebAssembly in 113.03ms.
INFO [dev] Watching for file changes...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'port')
  port = (server.addrs[0] as Deno.NetAddr).port;
                                           ^
    at serve (https://deno.land/std@0.155.0/http/server.ts:591:44)
    at serve (https://deno.land/x/aleph@1.0.0-beta.21/server/mod.ts:407:5)
    at serve (https://deno.land/x/aleph@1.0.0-beta.21/runtime/react/server.ts:40:3)
    at file:///Users/didi/Desktop/projects/deno-react/server.ts:3:1

**Comment by liwei511** [comment]
deno 1.28.1 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3

**Comment by liwei511** [comment]
MacOS 13

**Comment by liwei511** [comment]
错误位置：https://deno.land/std@0.155.0/http/server.ts?source=#L591

**Comment by liwei511** [comment]
when
```
deno run -A -r https://alephjs.org/init.ts
# choose react
cd my-app
deno task dev
```
