### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by kirilligum** [alephjs/aleph.js#535]
fish on ubuntu wsl
```
kirill@zagadka ~/t/deno> curl -fsSL https://deno.land/x/install/install.sh | sh

######################################################################## 100.0%
Archive:  /home/kirill/.deno/bin/deno.zip
  inflating: /home/kirill/.deno/bin/deno
Deno was installed successfully to /home/kirill/.deno/bin/deno
Manually add the directory to your $HOME/.bashrc (or similar)
  export DENO_INSTALL="/home/kirill/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"
Run '/home/kirill/.deno/bin/deno --help' to get started

Stuck? Join our Discord https://discord.gg/deno
kirill@zagadka ~/t/deno> set -U DENO_INSTALL /home/kirill/.deno
kirill@zagadka ~/t/deno> echo $DENO_INSTALL
/home/kirill/.deno
kirill@zagadka ~/t/deno> fish_add_path $DENO_INSTALL/bin
kirill@zagadka ~/t/deno> deno
Could not set npm package requirements. Error getting response at https://registry.npmjs.org/ethers for package "ethers": An npm specifier not found in cache: "ethers", --cached-only is specified.
Deno 1.31.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
>
kirill@zagadka ~/t/deno> deno run -A -r https://alephjs.org/init.ts

? Project Name: try
? Select a framework:
  1. React
  2. React with MDX
  3. Vue
  4. Yew
  5. Leptos
  6. Solid
  7. REST API
[1-7] 1
? Generate `_export.ts` file for runtime that doesn't support dynamic import (deploy to Deno Deploy)? [y/N] N
? Using Unocss(TailwindCSS)? [y/N]
? Initialize VS Code workspace configuration? [y/N] N
↓ Downloading template(react), this might take a moment...

▲ Aleph.js is ready to go!

$ cd try
$ deno task dev    # Start the server in `development` mode
$ deno task start  # Start the server in `production` mode
$ deno task build  # Build & Optimize the app (bundling, SSG, etc.)

Docs: https://alephjs.org/docs
Bugs: https://github.com/alephjs/aleph.js/issues

kirill@zagadka ~/t/deno> cd try/
kirill@zagadka ~/t/d/try> deno task dev
Task dev deno run -A dev.ts
INFO [dev] Watching for file changes...
INFO Server ready on http://localhost:8000
^C⏎
kirill@zagadka ~/t/d/try [SIGINT]> deno task start
Task start deno run -A server.ts
INFO Server ready on http://localhost:8000
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
                  controller.close();
                             ^
    at ReadableStreamDefaultController.close (internal:deno_web/06_streams.js:5425:13)
    at send (https://deno.land/x/aleph@1.0.0-beta.24/server/renderer.ts:260:30)
kirill@zagadka ~/t/d/try [1]> deno task build
Task build deno run -A server.ts --build
INFO 0 routes found
INFO 3 client modules built
INFO Done in 3781.38ms
kirill@zagadka ~/t/d/try> deno task start
Task start deno run -A server.ts
INFO Server ready on http://localhost:8000
^C⏎
kirill@zagadka ~/t/d/try [SIGINT]> deno task dev
Task dev deno run -A dev.ts
INFO [dev] Watching for file changes...
INFO Server ready on http://localhost:8000
^C⏎
kirill@zagadka ~/t/d/try [SIGINT]> deno task start
Task start deno run -A server.ts
INFO Server ready on http://localhost:8000
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
                  controller.close();
                             ^
    at ReadableStreamDefaultController.close (internal:deno_web/06_streams.js:5425:13)
    at send (https://deno.land/x/aleph@1.0.0-beta.24/server/renderer.ts:260:30)
kirill@zagadka ~/t/d/try [1]>
```

**Comment by ije** [comment]
does the `dev` mode fail too?

**Comment by kirilligum** [comment]
no
you can see above
```
kirill@zagadka ~/t/d/try> deno task dev
Task dev deno run -A dev.ts
INFO [dev] Watching for file changes...
INFO Server ready on http://localhost:8000
^C⏎
```

**Comment by kirilligum** [comment]
the browser shows the website

**Comment by kirilligum** [comment]
if i run start after build, i don't get the error in the terminal anymore but the website reloads into an error
![image](https://user-images.githubusercontent.com/1944021/221813465-b6c2e4c7-22dc-4705-9ee1-00050811f6ca.png)

`Cannot read properties of null (reading 'useContext')`

**Comment by ije** [comment]
thanks! i can repeat on my computer! will fix it ASAP

**Comment by ije** [comment]
<img width="789" alt="Screenshot 2023-02-28 at 18 18 50" src="https://user-images.githubusercontent.com/2883484/221825178-9b74c675-5d7a-4c7f-9ddc-581024ac4db6.png">

**Comment by ije** [comment]
this only happens when i released the framework, and the integration testing passed

**Comment by ije** [comment]
now should work fine
