### ISSUE TITLE
"Buffer.from is not a function" when using ESM package

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#69]
Hey, I'm trying to use [web3](https://github.com/ethereum/web3.js/) from ESM

```typescript
import Web3 from "https://esm.sh/web3"

export default function Home() {
  return null;
}
```

But when loading the page I'm getting this error

```
TypeError: Buffer.from is not a function
    at varintEncode (file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31889:23)
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31900:37
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:31930:33
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34701:18
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34738:23
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:69:9
    at file:///.../.aleph/development.es2018/-/cdn.esm.sh/v11/web3@1.3.1/es2018/web3.development.js:34833:23
```

**Comment by shadowtime2000** [comment]
I am going to close this issue because this is not the repo for esm.sh, please open issues related to esm.sh [in the esm.sh repo](https://github.com/postui/esm.sh)
