### ISSUE TITLE
Doesn't work with Microsoft's FluentUI

### ISSUE THREAD

**Issue by FallingSnow** [alephjs/aleph.js#75]
Component:
```jsx
import React from 'https://esm.sh/react'
import { PrimaryButton } from 'https://esm.sh/@fluentui/react';

export default function Button({ width = 75 }: { width?: number }) {
    return (
        <PrimaryButton/>
    )
}
```

Console:
```js
ERROR TypeError: head.insertBefore is not a function
    at Stylesheet6._createStyleElement (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:254:22)
    at Stylesheet6._getStyleElement (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:226:39)
    at Stylesheet6.insertRule (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:181:67)
    at applyRegistration (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:695:29)
    at styleToClassName (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:708:9)
    at mergeCss (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:725:22)
    at mergeStyles (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:719:12)
    at file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:1520:31
```

Browser:
```js
TypeError: Cannot read property 'deno' of null
    at Home (http://localhost:8080/_aleph/pages/index.4d9dac55d.js:48:21)
    at renderWithHooks (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:11639:32)
    at mountIndeterminateComponent (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:13826:29)
    at beginWork (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:14651:32)
    at HTMLUnknownElement.callCallback2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:4054:34)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:4080:34)
    at invokeGuardedCallback (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:4115:45)
    at beginWork$1 (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:17853:25)
    at performUnitOfWork (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:17055:28)
    at workLoopSync (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:17007:21)
```

If you use `"ssr": false, // SPA mode` you still end up with the same browser error message. But no console error message.

**Comment by shadowtime2000** [comment]
@FallingSnow Is the component a page or just a component which is used in a page? If it is a component which is used in a page could you share the page it is used in?

**Comment by FallingSnow** [comment]
It was used in a page. I've created a minimal repo where there is only 2 additions, the import and usage.

https://github.com/FallingSnow/aleph.js-issue-75/blob/6d9e20809ce3c2d7031a541dd945225b765b60d2/app.tsx#L3

**Comment by shadowtime2000** [comment]
It seems to be that the reason that the SPA mode is failing is because `useDeno` is being used, but I don't think that is supported in SPA mode because it is meant for build time in SSR/SSG. I am going to look more into why `useDeno` is failing in SSR/SSG and I think the `insertBefore` problem is with `insertBefore` not being implemented in [the Deno DOM Virtual Element class](https://github.com/alephjs/aleph.js/blob/master/project.ts#L597) but I am not sure. I will look into implementing `insertBefore` and related methods in the virtual SSR DOM.

**Comment by ije** [comment]
maybe we can add **ssr** support in `app.tsx`, please ref https://github.com/microsoft/fluentui/blob/2858fcaf942682621467b87aaef5d1be47f8ce47/packages/utilities/src/dom/setSSR.ts

**Comment by FallingSnow** [comment]
Oh you're right, if you remove `useDeno` there is a new error
```js
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react@16.14.0/es2018/react.development.js:790:31)
    at useEffect2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react@16.14.0/es2018/react.development.js:816:66)
    at useFocusRects (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:2687:5)
    at FocusRects (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/@fluentui/react@7.155.3/es2018/react.development.js:2713:37)
    at renderWithHooks (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:9106:32)
    at mountIndeterminateComponent (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:10439:29)
    at beginWork (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:11215:32)
    at HTMLUnknownElement.callCallback2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:2701:97)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:2724:34)
    at invokeGuardedCallback (http://localhost:8080/_aleph/-/cdn.esm.sh/v13/react-dom@17.0.1/es2018/react-dom.development.js:2751:151)
```

Could this be caused because there are two different reacts imported when doing
```jsx
import React, { useState } from 'https://esm.sh/react'
import { PrimaryButton } from 'https://esm.sh/@fluentui/react'
```

**Comment by shadowtime2000** [comment]
@FallingSnow Yeah, it is probably because of 2 different React's being pulled in. @ije and I discussed this in #59, and we decided that a `?external=some-library@some-other-library-link` would best fit. I can't remember off the top of my head if having the library use the same version of React would fix this problem though.

**Comment by FallingSnow** [comment]
I don't think it does. I'm using the following and the error remains.

```jsx
import React, { useState } from 'https://esm.sh/react@16.8.6?dev'
import { PrimaryButton } from 'https://esm.sh/@fluentui/react?external=react@16.8.6'
```

**Comment by shadowtime2000** [comment]
@FallingSnow I don't believe `?external` has been implemented yet, I was just pointing out that once that is implemented it could be a possible solution.

**Comment by FallingSnow** [comment]
Oh, I see. Thanks for pointing that out.

For what it's worth, I tried loading with jspm and got the same error.

Skypack gave me this error, which seems completely off (`BaseExtendedPeoplePicker` in `dateMath.js`...)
```js
Uncaught (in promise) SyntaxError: The requested module '../../@fluentui/date-time-utilities@v7.9.0-ZJuUiWC8BJzkUCRviSZe/dist=es2020,mode=raw/lib/dateMath/dateMath.js' does not provide an export named 'BaseExtendedPeoplePicker'
```

**Comment by ije** [comment]
```js
import React, { useState } from 'https://esm.sh/react'
import { PrimaryButton } from 'https://esm.sh/@fluentui/react?external=react@17.0.1'
```
does this work?

**Comment by ije** [comment]
since aleph uses react 17.0.1 as default.

**Comment by ije** [comment]
and please try to delete the `_aleph` folder to avoid esm.sh CDN conflict because i updated the esm.sh server yesterday.

**Comment by FallingSnow** [comment]
Easy peasy lemon squeezy, works! Wow that was rather painless and simple. Thanks!

**Comment by ije** [comment]
cool!

**Comment by FallingSnow** [comment]
Should point out that while in SSR mode, you still get the following in the console. It also flashes in the browser when first loading the page, then disappears and displays normal.

```js
ERROR TypeError: head.insertBefore is not a function
    at Stylesheet6._createStyleElement (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:177:22)
    at Stylesheet6._getStyleElement (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:151:39)
    at Stylesheet6.insertRule (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:120:67)
    at applyRegistration (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:532:29)
    at styleToClassName (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:545:9)
    at mergeCss (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:561:22)
    at mergeStyles (file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:555:12)
    at file:///home/ayrton/Coding/node/mmes/server/.aleph/development.es2018/-/cdn.esm.sh/v14/@fluentui/react@7.155.3/external=react@17.0.1/es2018/react.development.js:1247:31
```

Nether is experienced when using `"ssr": false, // SPA mode`.

**Comment by ije** [comment]
maybe you need the **[Asynchronous Import](https://alephjs.org/docs/advanced-features/asynchronous-import)** .

**Comment by FallingSnow** [comment]
Does this mean I'd have to use `<Import>` on everything component uses a `@fluentui/react` component?

**Comment by c0per** [comment]
> ```js
> ```js
> import React, { useState } from 'https://esm.sh/react'
> import { PrimaryButton } from 'https://esm.sh/@fluentui/react?external=react@17.0.1'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> does this work?
> ```

I'm facing the same issue with Material-UI. I replaced "external" to "deps", and it worked. Maybe the "external" hasn't been implemented yet.

**Comment by ije** [comment]
@c0per `?external` has been moved to `?deps`
