### ISSUE TITLE
By incompatible, TypeError: Argument of type 'TransformerFactory<SourceFile>'

### ISSUE THREAD

**Issue by yoshixmk** [alephjs/aleph.js#81]
using Deno 1.6.3:
```bash
$ deno run -A https://deno.land/x/aleph@v0.2.26/cli.ts build
```

Error log:
```ts
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type 'TransformerFactory<SourceFile>' is not assignable to parameter of type 'TransformerFactory<SourceFile> | CustomTransformerFactory'.
  Type 'import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").SourceFile>' is not assignable to type 'import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").SourceFile>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").TransformationContext' is not assignable to type 'import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").TransformationContext'.
        Types of property 'isSubstitutionEnabled' are incompatible.
          Type '(node: import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").Node) => boolean' is not assignable to type '(node: import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").Node) => boolean'.
            Types of parameters 'node' and 'node' are incompatible.
              Type 'import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").Node' is not assignable to type 'import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").Node'.
                Types of property 'kind' are incompatible.
                  Type 'import("https://cdn.esm.sh/v14/typescript@4.1.3/lib/typescript.d.ts").SyntaxKind' is not assignable to type 'import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").SyntaxKind'.
                    Property 'IntrinsicKeyword' is missing in type 'import("https://cdn.esm.sh/v14/typescript@4.0.5/lib/typescript.d.ts").SyntaxKind'.
    if (reactRefresh) transformers.before!.push(reactRefreshTS())
```

This is my project, [https://deno.land/x/piny](https://deno.land/x/piny)
Is there a solution, such as explicitly specifying the version for CDN?

**Comment by shadowtime2000** [comment]
seems to just be a type checking problem with the current compiler which is basic `tsc`, #28 could possibly fix this. I will look deeper into this later.

**Comment by yoshixmk** [comment]
Grate, thx!

**Comment by ije** [comment]
please use aleph v0.2.27 that should work

**Comment by yoshixmk** [comment]
I was able to confirm that it was fixed

**Comment by shackra** [comment]
I can reproduce this bug:

```
Download https://deno.land/x/aleph@v0.2.27/vendor/deno-dom/parser.ts
Check https://deno.land/x/aleph@v0.2.27/cli/dev.ts
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type 'TransformerFactory<SourceFile>' is not assignable to parameter of type 'TransformerFactory<SourceFile> | CustomTransformerFactory'.
  Type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").SourceFile>' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").SourceFile>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").TransformationContext' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").TransformationContext'.
        The types of 'factory.createTypeParameterDeclaration(...).parent' are incompatible between these types.
          Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").InferTypeNode' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").InferTypeNode'.
            Type 'JSDocTemplateTag' is not assignable to type 'DeclarationWithTypeParameterChildren | InferTypeNode'.
              Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDocTemplateTag' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDocTemplateTag'.
                Types of property 'parent' are incompatible.
                  Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDocTypeLiteral' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDocTypeLiteral'.
                    Type 'JSDoc' is not assignable to type 'JSDoc | JSDocTypeLiteral'.
                      Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDoc' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDoc'.
                        Types of property 'parent' are incompatible.
                          Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").HasJSDoc' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").HasJSDoc'.
                            Type 'ImportEqualsDeclaration' is not assignable to type 'HasJSDoc'.
                              Property 'isTypeOnly' is missing in type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").ImportEqualsDeclaration' but required in type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").ImportEqualsDeclaration'.
    if (reactRefresh) transformers.before!.push(reactRefreshTS())
                                                ~~~~~~~~~~~~~~~~
    at https://deno.land/x/aleph@v0.2.27/tsc/compile.ts:28:49

    'isTypeOnly' is declared here.
            readonly isTypeOnly: boolean;
                     ~~~~~~~~~~
        at https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts:1601:18
    const { default: cmd } = await import(`./cli/${command}.ts`)
                             ^
    at async main (https://deno.land/x/aleph@v0.2.27/cli.ts:163:30)
```

**Comment by shackra** [comment]
I tried with `0.2.28` first and then with `0.2.27`

**Comment by shackra** [comment]
same error? different version of aleph cli (`0.2.28`)

```
❯ aleph dev
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) TypeError: TS2345 [ERROR]: Argument of type 'TransformerFactory<SourceFile>' is not assignable to parameter of type 'TransformerFactory<SourceFile> | CustomTransformerFactory'.
  Type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").SourceFile>' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").TransformerFactory<import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").SourceFile>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").TransformationContext' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").TransformationContext'.
        The types of 'factory.createTypeParameterDeclaration(...).parent' are incompatible between these types.
          Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").InferTypeNode' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").DeclarationWithTypeParameterChildren | import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").InferTypeNode'.
            Type 'JSDocTemplateTag' is not assignable to type 'DeclarationWithTypeParameterChildren | InferTypeNode'.
              Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDocTemplateTag' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDocTemplateTag'.
                Types of property 'parent' are incompatible.
                  Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDocTypeLiteral' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDoc | import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDocTypeLiteral'.
                    Type 'JSDoc' is not assignable to type 'JSDoc | JSDocTypeLiteral'.
                      Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").JSDoc' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").JSDoc'.
                        Types of property 'parent' are incompatible.
                          Type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").HasJSDoc' is not assignable to type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").HasJSDoc'.
                            Type 'ImportEqualsDeclaration' is not assignable to type 'HasJSDoc'.
                              Property 'isTypeOnly' is missing in type 'import("https://cdn.esm.sh/v38/typescript@4.1.2/lib/typescript.d.ts").ImportEqualsDeclaration' but required in type 'import("https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts").ImportEqualsDeclaration'.
    if (reactRefresh) transformers.before!.push(reactRefreshTS())
                                                ~~~~~~~~~~~~~~~~
    at https://deno.land/x/aleph@v0.2.28/tsc/compile.ts:28:49

    'isTypeOnly' is declared here.
            readonly isTypeOnly: boolean;
                     ~~~~~~~~~~
        at https://cdn.esm.sh/v38/typescript@4.2.3/lib/typescript.d.ts:1601:18
    const { default: cmd } = await import(`./cli/${command}.ts`)
                             ^
    at async main (https://deno.land/x/aleph@v0.2.28/cli.ts:163:30)
```

**Comment by ije** [comment]
@shackra try alpha.25 instead, i will release a beta version and update the docs this week

**Comment by shackra** [comment]
> @shackra try 0.3.0-alpha.25 instead, i will release a beta version and update the docs this week

that did it, thanks!

**Comment by Type1J** [comment]
With deno 1.9.0, I needed Aleph 0.3.0-alpha.27 (25 and 26 didn't work).
